// This system-verilog module was generated by Vega
//               Please do not edit!

//---------------------------------------------------------------------------
//                                                                           
//              Inspur Confidential                                          
// Copyright (c) 2021 Inspur. All rights reserved
//                                                                           
// File    : /nfs/work/shared/aipu.work/dingzhiming/workspace/dingzhiming.aipu.default/env_repo/design_repo/rtl/soc_top/rtl/sv/core_top.sv
// Author  : Inspur Xi'an R&D                                                
// History : 2021-Sep-29 11:27:34 AM - Created    
//                                                                           
//---------------------------------------------------------------------------

module core_top(
    user_rst,
    u_uncore_top_riscv_clk_i,
    u_uncore_top_riscv_core_clk_i,
    u_uncore_top_riscv_rst_i,
    u_uncore_top_riscv_debug_clk_i,
    u_uncore_top_riscv_debug_rst_i,
    u_uncore_top_riscv_rtc_toggle_i,
    u_uncore_top_dla_csb_clk_i,
    u_uncore_top_dla_core_clk_i,
    u_uncore_top_mac_rst_n_i,
    u_uncore_top_dma_clk_i,
    u_uncore_top_dma_rst_n_i,
    u_uncore_top_per_clk_i,
    u_uncore_top_core_nic_rst_n_i,
    por_rstn_sync,
    u_soc_top_PCIE_EP_REFCLK_p_i,
    u_soc_top_PCIE_EP_REFCLK_n_i,
    u_soc_top_PCIE_EP_nPRESET_i,
    u_xdma_0_top_axi_aclk_s,
    u_xdma_0_top_axi_aresetn_o,
    u_soc_top_DDR4_REF_CLK_p_i,
    u_soc_top_DDR4_REF_CLK_n_i,
    u_uncore_top_ddr_rst_i,
    u_soc_top_TCK_i,
    u_soc_top_TRST_n_i,
    u_tdi_rmux_z_i,
    u_tms_rmux_z_i,
    debug_systemjtag_jtag_TDO_driven,
    u_SiFive_CoreIPSubsystem_debug_systemjtag_jtag_TDO_data_o,
    riscv_debug_dmactive,
    riscv_debug_dmactiveack,
    msi_enable_o,
    msix_enable_o,
    msi_vector_width_o,
    usr_irq_req_i,
    usr_irq_ack_o,
    u_xdma_0_top_user_lnk_up_o,
    u_xdma_0_top_pci_exp_txp_o,
    u_xdma_0_top_pci_exp_txn_o,
    u_soc_top_PCIE_EP_EXP_RX_p_i,
    u_soc_top_PCIE_EP_EXP_RX_n_i,
    u_ddr4_0_top_c0_ddr4_act_n_o,
    u_ddr4_0_top_c0_ddr4_ck_t_o,
    u_ddr4_0_top_c0_ddr4_ck_c_o,
    u_ddr4_0_top_c0_ddr4_reset_n_o,
    u_ddr4_0_top_c0_ddr4_adr_o,
    u_ddr4_0_top_c0_ddr4_ba_o,
    u_ddr4_0_top_c0_ddr4_bg_o,
    u_ddr4_0_top_c0_ddr4_cs_n_o,
    u_ddr4_0_top_c0_ddr4_cke_o,
    u_ddr4_0_top_c0_ddr4_odt_o,
    u_ddr4_0_top_c0_ddr4_dm_dbi_n,
    u_ddr4_0_top_c0_ddr4_dq,
    u_ddr4_0_top_c0_ddr4_dqs_c,
    u_ddr4_0_top_c0_ddr4_dqs_t,
    u_ddr4_0_top_c0_init_calib_complete_o,
    u_uncore_top_AWID_AXI_CORE_MST_o,
    u_uncore_top_AWVALID_AXI_CORE_MST_o,
    u_uncore_top_AWREADY_AXI_CORE_MST_i,
    u_uncore_top_AWADDR_AXI_CORE_MST_o,
    u_uncore_top_AWLEN_AXI_CORE_MST_o,
    u_uncore_top_AWSIZE_AXI_CORE_MST_o,
    u_uncore_top_AWBURST_AXI_CORE_MST_o,
    u_uncore_top_AWLOCK_AXI_CORE_MST_o,
    u_uncore_top_AWCACHE_AXI_CORE_MST_o,
    u_uncore_top_AWPROT_AXI_CORE_MST_o,
    u_uncore_top_WVALID_AXI_CORE_MST_o,
    u_uncore_top_WREADY_AXI_CORE_MST_i,
    u_uncore_top_WLAST_AXI_CORE_MST_o,
    u_uncore_top_WDATA_AXI_CORE_MST_o,
    u_uncore_top_WSTRB_AXI_CORE_MST_o,
    u_uncore_top_BID_AXI_CORE_MST_i,
    u_uncore_top_BVALID_AXI_CORE_MST_i,
    u_uncore_top_BREADY_AXI_CORE_MST_o,
    u_uncore_top_BRESP_AXI_CORE_MST_i,
    u_uncore_top_ARID_AXI_CORE_MST_o,
    u_uncore_top_ARVALID_AXI_CORE_MST_o,
    u_uncore_top_ARREADY_AXI_CORE_MST_i,
    u_uncore_top_ARADDR_AXI_CORE_MST_o,
    u_uncore_top_ARLEN_AXI_CORE_MST_o,
    u_uncore_top_ARSIZE_AXI_CORE_MST_o,
    u_uncore_top_ARBURST_AXI_CORE_MST_o,
    u_uncore_top_ARLOCK_AXI_CORE_MST_o,
    u_uncore_top_ARCACHE_AXI_CORE_MST_o,
    u_uncore_top_ARPROT_AXI_CORE_MST_o,
    u_uncore_top_RID_AXI_CORE_MST_i,
    u_uncore_top_RVALID_AXI_CORE_MST_i,
    u_uncore_top_RREADY_AXI_CORE_MST_o,
    u_uncore_top_RLAST_AXI_CORE_MST_i,
    u_uncore_top_RDATA_AXI_CORE_MST_i,
    u_uncore_top_RRESP_AXI_CORE_MST_i,
    u_uncore_top_timer0_int_cmp_i,
    u_uncore_top_timer0_int_ovf_i,
    u_uncore_top_timer1_int_cmp_i,
    u_uncore_top_timer1_int_ovf_i,
    u_uncore_top_sw_int0_i,
    u_uncore_top_sw_int1_i,
    u_uncore_top_scu_int_i,
    u_uncore_top_uart_int_i
);

input          user_rst;
input          u_uncore_top_riscv_clk_i;
input          u_uncore_top_riscv_core_clk_i;
input          u_uncore_top_riscv_rst_i;
input          u_uncore_top_riscv_debug_clk_i;
input          u_uncore_top_riscv_debug_rst_i;
input          u_uncore_top_riscv_rtc_toggle_i;
input          u_uncore_top_dla_csb_clk_i;
input          u_uncore_top_dla_core_clk_i;
input          u_uncore_top_mac_rst_n_i;
input          u_uncore_top_dma_clk_i;
input          u_uncore_top_dma_rst_n_i;
input          u_uncore_top_per_clk_i;
input          u_uncore_top_core_nic_rst_n_i;
input          por_rstn_sync;
input          u_soc_top_PCIE_EP_REFCLK_p_i;
input          u_soc_top_PCIE_EP_REFCLK_n_i;
input          u_soc_top_PCIE_EP_nPRESET_i;
output         u_xdma_0_top_axi_aclk_s;
output         u_xdma_0_top_axi_aresetn_o;
input          u_soc_top_DDR4_REF_CLK_p_i;
input          u_soc_top_DDR4_REF_CLK_n_i;
input          u_uncore_top_ddr_rst_i;

input          u_soc_top_TCK_i;
input          u_soc_top_TRST_n_i;
input          u_tdi_rmux_z_i;
input          u_tms_rmux_z_i;
output         debug_systemjtag_jtag_TDO_driven;
output         u_SiFive_CoreIPSubsystem_debug_systemjtag_jtag_TDO_data_o;

output         riscv_debug_dmactive;
input          riscv_debug_dmactiveack;

input  [2 : 0] usr_irq_req_i;
output [2 : 0] usr_irq_ack_o;
output         msi_enable_o;
output         msix_enable_o;
output [2 : 0] msi_vector_width_o;
output         u_xdma_0_top_user_lnk_up_o;
output [1 : 0] u_xdma_0_top_pci_exp_txp_o;
output [1 : 0] u_xdma_0_top_pci_exp_txn_o;
input  [1:0]   u_soc_top_PCIE_EP_EXP_RX_p_i;
input  [1:0]   u_soc_top_PCIE_EP_EXP_RX_n_i;

output         u_ddr4_0_top_c0_ddr4_act_n_o;
output [0:0]   u_ddr4_0_top_c0_ddr4_ck_t_o;
output [0:0]   u_ddr4_0_top_c0_ddr4_ck_c_o;
output         u_ddr4_0_top_c0_ddr4_reset_n_o;
output [16:0]  u_ddr4_0_top_c0_ddr4_adr_o;
output [1:0]   u_ddr4_0_top_c0_ddr4_ba_o;
output [1:0]   u_ddr4_0_top_c0_ddr4_bg_o;
output [0:0]   u_ddr4_0_top_c0_ddr4_cs_n_o;
output [0:0]   u_ddr4_0_top_c0_ddr4_cke_o;
output [0:0]   u_ddr4_0_top_c0_ddr4_odt_o;
inout  [8:0]   u_ddr4_0_top_c0_ddr4_dm_dbi_n;
inout  [71:0]  u_ddr4_0_top_c0_ddr4_dq;
inout  [8:0]   u_ddr4_0_top_c0_ddr4_dqs_c;
inout  [8:0]   u_ddr4_0_top_c0_ddr4_dqs_t;
output         u_ddr4_0_top_c0_init_calib_complete_o;

output [10:0]  u_uncore_top_AWID_AXI_CORE_MST_o;
output         u_uncore_top_AWVALID_AXI_CORE_MST_o;
input          u_uncore_top_AWREADY_AXI_CORE_MST_i;
output [31:0]  u_uncore_top_AWADDR_AXI_CORE_MST_o;
output [7:0]   u_uncore_top_AWLEN_AXI_CORE_MST_o;
output [2:0]   u_uncore_top_AWSIZE_AXI_CORE_MST_o;
output [1:0]   u_uncore_top_AWBURST_AXI_CORE_MST_o;
output         u_uncore_top_AWLOCK_AXI_CORE_MST_o;
output [3:0]   u_uncore_top_AWCACHE_AXI_CORE_MST_o;
output [2:0]   u_uncore_top_AWPROT_AXI_CORE_MST_o;
output         u_uncore_top_WVALID_AXI_CORE_MST_o;
input          u_uncore_top_WREADY_AXI_CORE_MST_i;
output         u_uncore_top_WLAST_AXI_CORE_MST_o;
output [31:0]  u_uncore_top_WDATA_AXI_CORE_MST_o;
output [3:0]   u_uncore_top_WSTRB_AXI_CORE_MST_o;
input  [10:0]  u_uncore_top_BID_AXI_CORE_MST_i;
input          u_uncore_top_BVALID_AXI_CORE_MST_i;
output         u_uncore_top_BREADY_AXI_CORE_MST_o;
input  [1:0]   u_uncore_top_BRESP_AXI_CORE_MST_i;
output [10:0]  u_uncore_top_ARID_AXI_CORE_MST_o;
output         u_uncore_top_ARVALID_AXI_CORE_MST_o;
input          u_uncore_top_ARREADY_AXI_CORE_MST_i;
output [31:0]  u_uncore_top_ARADDR_AXI_CORE_MST_o;
output [7:0]   u_uncore_top_ARLEN_AXI_CORE_MST_o;
output [2:0]   u_uncore_top_ARSIZE_AXI_CORE_MST_o;
output [1:0]   u_uncore_top_ARBURST_AXI_CORE_MST_o;
output         u_uncore_top_ARLOCK_AXI_CORE_MST_o;
output [3:0]   u_uncore_top_ARCACHE_AXI_CORE_MST_o;
output [2:0]   u_uncore_top_ARPROT_AXI_CORE_MST_o;
input  [10:0]  u_uncore_top_RID_AXI_CORE_MST_i;
input          u_uncore_top_RVALID_AXI_CORE_MST_i;
output         u_uncore_top_RREADY_AXI_CORE_MST_o;
input  [31:0]  u_uncore_top_RDATA_AXI_CORE_MST_i;
input  [1:0]   u_uncore_top_RRESP_AXI_CORE_MST_i;
input          u_uncore_top_RLAST_AXI_CORE_MST_i;

input          u_uncore_top_timer0_int_cmp_i;
input          u_uncore_top_timer0_int_ovf_i;
input          u_uncore_top_timer1_int_cmp_i;
input          u_uncore_top_timer1_int_ovf_i;
input          u_uncore_top_sw_int0_i;
input          u_uncore_top_sw_int1_i;
input          u_uncore_top_scu_int_i;
input          u_uncore_top_uart_int_i;


// input wires
wire             u_uncore_top_riscv_clk_s;
wire             u_uncore_top_riscv_core_clk_s;
wire             u_uncore_top_riscv_rst_s;
wire             u_uncore_top_riscv_debug_clk_s;
wire             u_uncore_top_riscv_debug_rst_s;
wire             u_uncore_top_riscv_rtc_toggle_s;
wire             u_uncore_top_dla_csb_clk_s;
wire             u_uncore_top_dla_core_clk_s;
wire             u_uncore_top_mac_rst_n_s;
wire             u_uncore_top_per_clk_s;
wire             u_uncore_top_core_nic_rst_n_s;
wire             u_uncore_top_dma_clk_s;
wire             u_uncore_top_dma_rst_n_s;
wire             u_soc_top_PCIE_EP_REFCLK_n_s;
wire             u_soc_top_PCIE_EP_REFCLK_p_s;
(*mark_debug = "TRUE"*)wire             u_soc_top_PCIE_EP_nPRESET_s;
wire             u_soc_top_DDR4_REF_CLK_n_s;
wire             u_soc_top_DDR4_REF_CLK_p_s;
wire             u_uncore_top_ddr_rst_s;
wire             u_soc_top_TCK_s;
wire             u_soc_top_TRST_n_s;
wire             u_tdi_rmux_z_s;
wire             u_tms_rmux_z_s;
/*(*mark_debug = "TRUE"*)*/wire [1:0]       u_soc_top_PCIE_EP_EXP_RX_n_s;
/*(*mark_debug = "TRUE"*)*/wire [1:0]       u_soc_top_PCIE_EP_EXP_RX_p_s;

// output wires
wire             u_SiFive_CoreIPSubsystem_debug_systemjtag_jtag_TDO_data_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_axi_aresetn_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_user_lnk_up_s;
/*(*mark_debug = "TRUE"*)*/wire [1:0]       u_xdma_0_top_pci_exp_txn_s;
/*(*mark_debug = "TRUE"*)*/wire [1:0]       u_xdma_0_top_pci_exp_txp_s;
wire             u_ddr4_0_top_c0_ddr4_act_n_s;
wire [16:0]      u_ddr4_0_top_c0_ddr4_adr_s;
wire [1:0]       u_ddr4_0_top_c0_ddr4_ba_s;
wire [1:0]       u_ddr4_0_top_c0_ddr4_bg_s;
wire [0:0]       u_ddr4_0_top_c0_ddr4_ck_c_s;
wire [0:0]       u_ddr4_0_top_c0_ddr4_ck_t_s;
wire [0:0]       u_ddr4_0_top_c0_ddr4_cke_s;
wire [0:0]       u_ddr4_0_top_c0_ddr4_cs_n_s;
wire [0:0]       u_ddr4_0_top_c0_ddr4_odt_s;
wire             u_ddr4_0_top_c0_ddr4_reset_n_s;
wire             u_ddr4_0_top_c0_init_calib_complete_s;

// internal wires
wire             u_pcie_xclk_to_single_sys_clk_s;
wire             u_pcie_xclk_to_single_sys_clk_gt_s;
wire             u_ddr_rst_sync_dout_s;
wire             u_ddr4_0_top_c0_ddr4_ui_clk_s;
wire             u_ddr4_0_top_c0_ddr4_ui_clk_sync_rst_s;

(*mark_debug = "TRUE"*)wire             u_xdma_0_top_s_axil_awvalid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_s_axil_awready_s;
(*mark_debug = "TRUE"*)wire [31:0]      u_xdma_0_top_s_axil_awaddr_s;
                       wire [2:0]       u_xdma_0_top_s_axil_awprot_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_s_axil_wvalid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_s_axil_wready_s;
(*mark_debug = "TRUE"*)wire [31:0]      u_xdma_0_top_s_axil_wdata_s;
                       wire [3:0]       u_xdma_0_top_s_axil_wstrb_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_s_axil_bvalid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_s_axil_bready_s;
                       wire [1:0]       u_xdma_0_top_s_axil_bresp_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_s_axil_arvalid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_s_axil_arready_s;
(*mark_debug = "TRUE"*)wire [31:0]      u_xdma_0_top_s_axil_araddr_s;
                       wire [2:0]       u_xdma_0_top_s_axil_arprot_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_s_axil_rvalid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_s_axil_rready_s;
(*mark_debug = "TRUE"*)wire [31:0]      u_xdma_0_top_s_axil_rdata_s;
                       wire [1:0]       u_xdma_0_top_s_axil_rresp_s;

                       wire [3:0]       u_xdma_0_top_m_axi_awid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axi_awvalid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axi_awready_s;
(*mark_debug = "TRUE"*)wire [63:0]      u_xdma_0_top_m_axi_awaddr_s;
                       wire [7:0]       u_xdma_0_top_m_axi_awlen_s;
                       wire [2:0]       u_xdma_0_top_m_axi_awsize_s;
                       wire [1:0]       u_xdma_0_top_m_axi_awburst_s;
                       wire             u_xdma_0_top_m_axi_awlock_s;
                       wire [3:0]       u_xdma_0_top_m_axi_awcache_s;
                       wire [2:0]       u_xdma_0_top_m_axi_awprot_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axi_wvalid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axi_wready_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axi_wlast_s;
(*mark_debug = "TRUE"*)wire [63:0]      u_xdma_0_top_m_axi_wdata_s;
(*mark_debug = "TRUE"*)wire [7:0]       u_xdma_0_top_m_axi_wstrb_s;
                       wire [3:0]       u_xdma_0_top_m_axi_bid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axi_bvalid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axi_bready_s;
                       wire [1:0]       u_xdma_0_top_m_axi_bresp_s;
                       wire [3:0]       u_xdma_0_top_m_axi_arid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axi_arvalid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axi_arready_s;
(*mark_debug = "TRUE"*)wire [63:0]      u_xdma_0_top_m_axi_araddr_s;
                       wire [7:0]       u_xdma_0_top_m_axi_arlen_s;
                       wire [2:0]       u_xdma_0_top_m_axi_arsize_s;
                       wire [1:0]       u_xdma_0_top_m_axi_arburst_s;
                       wire             u_xdma_0_top_m_axi_arlock_s;
                       wire [3:0]       u_xdma_0_top_m_axi_arcache_s;
                       wire [2:0]       u_xdma_0_top_m_axi_arprot_s;
                       wire [3:0]       u_xdma_0_top_m_axi_rid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axi_rvalid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axi_rready_s;
(*mark_debug = "TRUE"*)wire [63:0]      u_xdma_0_top_m_axi_rdata_s;
                       wire [1:0]       u_xdma_0_top_m_axi_rresp_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axi_rlast_s;

(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axil_awvalid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axil_awready_s;
(*mark_debug = "TRUE"*)wire [31:0]      u_xdma_0_top_m_axil_awaddr_s;
                       wire [2:0]       u_xdma_0_top_m_axil_awprot_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axil_wvalid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axil_wready_s;
(*mark_debug = "TRUE"*)wire [31:0]      u_xdma_0_top_m_axil_wdata_s;
                       wire [3:0]       u_xdma_0_top_m_axil_wstrb_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axil_bvalid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axil_bready_s;
                       wire [1:0]       u_xdma_0_top_m_axil_bresp_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axil_arvalid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axil_arready_s;
(*mark_debug = "TRUE"*)wire [31:0]      u_xdma_0_top_m_axil_araddr_s;
                       wire [2:0]       u_xdma_0_top_m_axil_arprot_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axil_rvalid_s;
(*mark_debug = "TRUE"*)wire             u_xdma_0_top_m_axil_rready_s;
(*mark_debug = "TRUE"*)wire [31:0]      u_xdma_0_top_m_axil_rdata_s;
                       wire [1:0]       u_xdma_0_top_m_axil_rresp_s;

wire [12:0]      u_ddr4_0_top_c0_ddr4_s_axi_awid_s;
wire             u_ddr4_0_top_c0_ddr4_s_axi_awvalid_s;
wire             u_ddr4_0_top_c0_ddr4_s_axi_awready_s;
wire [63:0]      u_ddr4_0_top_c0_ddr4_s_axi_awaddr_s;
wire [7:0]       u_ddr4_0_top_c0_ddr4_s_axi_awlen_s;
wire [2:0]       u_ddr4_0_top_c0_ddr4_s_axi_awsize_s;
wire [1:0]       u_ddr4_0_top_c0_ddr4_s_axi_awburst_s;
wire             u_ddr4_0_top_c0_ddr4_s_axi_awlock_s;
wire [3:0]       u_ddr4_0_top_c0_ddr4_s_axi_awcache_s;
wire [2:0]       u_ddr4_0_top_c0_ddr4_s_axi_awprot_s;
wire             u_ddr4_0_top_c0_ddr4_s_axi_wvalid_s;
wire             u_ddr4_0_top_c0_ddr4_s_axi_wready_s;
wire             u_ddr4_0_top_c0_ddr4_s_axi_wlast_s;
wire [255:0]     u_ddr4_0_top_c0_ddr4_s_axi_wdata_s;
wire [31:0]      u_ddr4_0_top_c0_ddr4_s_axi_wstrb_s;
wire [12:0]      u_ddr4_0_top_c0_ddr4_s_axi_bid_s;
wire             u_ddr4_0_top_c0_ddr4_s_axi_bvalid_s;
wire             u_ddr4_0_top_c0_ddr4_s_axi_bready_s;
wire [1:0]       u_ddr4_0_top_c0_ddr4_s_axi_bresp_s;
wire [12:0]      u_ddr4_0_top_c0_ddr4_s_axi_arid_s;
wire             u_ddr4_0_top_c0_ddr4_s_axi_arvalid_s;
wire             u_ddr4_0_top_c0_ddr4_s_axi_arready_s;
wire [63:0]      u_ddr4_0_top_c0_ddr4_s_axi_araddr_s;
wire [7:0]       u_ddr4_0_top_c0_ddr4_s_axi_arlen_s;
wire [2:0]       u_ddr4_0_top_c0_ddr4_s_axi_arsize_s;
wire [1:0]       u_ddr4_0_top_c0_ddr4_s_axi_arburst_s;
wire             u_ddr4_0_top_c0_ddr4_s_axi_arlock_s;
wire [3:0]       u_ddr4_0_top_c0_ddr4_s_axi_arcache_s;
wire [2:0]       u_ddr4_0_top_c0_ddr4_s_axi_arprot_s;
wire [12:0]      u_ddr4_0_top_c0_ddr4_s_axi_rid_s;
wire             u_ddr4_0_top_c0_ddr4_s_axi_rvalid_s;
wire             u_ddr4_0_top_c0_ddr4_s_axi_rready_s;
wire [255:0]     u_ddr4_0_top_c0_ddr4_s_axi_rdata_s;
wire [1:0]       u_ddr4_0_top_c0_ddr4_s_axi_rresp_s;
wire             u_ddr4_0_top_c0_ddr4_s_axi_rlast_s;

wire             u_NV_nvdla_top_pselX_s;
wire             u_NV_nvdla_top_penable_s;
wire [31:0]      u_NV_nvdla_top_paddr_s;
wire             u_NV_nvdla_top_pwrite_s;
wire [31:0]      u_NV_nvdla_top_pwdata_s;
wire [31:0]      u_NV_nvdla_top_prdata_s;
wire             u_NV_nvdla_top_pready_s;
wire             u_NV_nvdla_top_pslverr_s;

wire [3:0]       u_NV_nvdla_top_nvdla_core2dbb_aw_awid_s;
wire             u_NV_nvdla_top_nvdla_core2dbb_aw_awvalid_s;
wire             u_NV_nvdla_top_nvdla_core2dbb_aw_awready_s;
wire [64 -1:0]   u_NV_nvdla_top_nvdla_core2dbb_aw_awaddr_s;
wire [7:0]       u_NV_nvdla_top_nvdla_core2dbb_aw_awlen_s;
wire [2:0]       u_NV_nvdla_top_nvdla_core2dbb_aw_awsize_s;
wire [1:0]       u_NV_nvdla_top_nvdla_core2dbb_aw_awburst_s;
wire             u_NV_nvdla_top_nvdla_core2dbb_aw_awlock_s;
wire [3:0]       u_NV_nvdla_top_nvdla_core2dbb_aw_awcache_s;
wire [2:0]       u_NV_nvdla_top_nvdla_core2dbb_aw_awprot_s;
wire             u_NV_nvdla_top_nvdla_core2dbb_w_wvalid_s;
wire             u_NV_nvdla_top_nvdla_core2dbb_w_wready_s;
wire             u_NV_nvdla_top_nvdla_core2dbb_w_wlast_s;
wire [256-1:0]   u_NV_nvdla_top_nvdla_core2dbb_w_wdata_s;
wire [256/8-1:0] u_NV_nvdla_top_nvdla_core2dbb_w_wstrb_s;
wire [3:0]       u_NV_nvdla_top_nvdla_core2dbb_b_bid_s;
wire             u_NV_nvdla_top_nvdla_core2dbb_b_bvalid_s;
wire             u_NV_nvdla_top_nvdla_core2dbb_b_bready_s;
wire [1:0]       u_NV_nvdla_top_nvdla_core2dbb_b_bresp_s;
wire [3:0]       u_NV_nvdla_top_nvdla_core2dbb_ar_arid_s;
wire             u_NV_nvdla_top_nvdla_core2dbb_ar_arvalid_s;
wire             u_NV_nvdla_top_nvdla_core2dbb_ar_arready_s;
wire [64 -1:0]   u_NV_nvdla_top_nvdla_core2dbb_ar_araddr_s;
wire [7:0]       u_NV_nvdla_top_nvdla_core2dbb_ar_arlen_s;
wire [2:0]       u_NV_nvdla_top_nvdla_core2dbb_ar_arsize_s;
wire [1:0]       u_NV_nvdla_top_nvdla_core2dbb_ar_arburst_s;
wire             u_NV_nvdla_top_nvdla_core2dbb_ar_arlock_s;
wire [3:0]       u_NV_nvdla_top_nvdla_core2dbb_ar_arcache_s;
wire [2:0]       u_NV_nvdla_top_nvdla_core2dbb_ar_arprot_s;
wire [3:0]       u_NV_nvdla_top_nvdla_core2dbb_r_rid_s;
wire             u_NV_nvdla_top_nvdla_core2dbb_r_rvalid_s;
wire             u_NV_nvdla_top_nvdla_core2dbb_r_rready_s;
wire [255:0]     u_NV_nvdla_top_nvdla_core2dbb_r_rdata_s;
wire [1:0]       u_NV_nvdla_top_nvdla_core2dbb_r_rresp_s;
wire             u_NV_nvdla_top_nvdla_core2dbb_r_rlast_s;

wire [3:0]       u_NV_nvdla_top_nvdla_core2cvsram_aw_awid_s;
wire             u_NV_nvdla_top_nvdla_core2cvsram_aw_awvalid_s;
wire             u_NV_nvdla_top_nvdla_core2cvsram_aw_awready_s;
wire [63:0]      u_NV_nvdla_top_nvdla_core2cvsram_aw_awaddr_s;
wire [7:0]       u_NV_nvdla_top_nvdla_core2cvsram_aw_awlen_s;
wire [2:0]       u_NV_nvdla_top_nvdla_core2cvsram_aw_awsize_s;
wire [1:0]       u_NV_nvdla_top_nvdla_core2cvsram_aw_awburst_s;
wire             u_NV_nvdla_top_nvdla_core2cvsram_aw_awlock_s;
wire [3:0]       u_NV_nvdla_top_nvdla_core2cvsram_aw_awcache_s;
wire [2:0]       u_NV_nvdla_top_nvdla_core2cvsram_aw_awprot_s;
wire             u_NV_nvdla_top_nvdla_core2cvsram_w_wvalid_s;
wire             u_NV_nvdla_top_nvdla_core2cvsram_w_wready_s;
wire             u_NV_nvdla_top_nvdla_core2cvsram_w_wlast_s;
wire [255:0]     u_NV_nvdla_top_nvdla_core2cvsram_w_wdata_s;
wire [31:0]      u_NV_nvdla_top_nvdla_core2cvsram_w_wstrb_s;
wire [3:0]       u_NV_nvdla_top_nvdla_core2cvsram_b_bid_s;
wire             u_NV_nvdla_top_nvdla_core2cvsram_b_bvalid_s;
wire             u_NV_nvdla_top_nvdla_core2cvsram_b_bready_s;
wire [1:0]       u_NV_nvdla_top_nvdla_core2cvsram_b_bresp_s;
wire [3:0]       u_NV_nvdla_top_nvdla_core2cvsram_ar_arid_s;
wire             u_NV_nvdla_top_nvdla_core2cvsram_ar_arvalid_s;
wire             u_NV_nvdla_top_nvdla_core2cvsram_ar_arready_s;
wire [63:0]      u_NV_nvdla_top_nvdla_core2cvsram_ar_araddr_s;
wire [7:0]       u_NV_nvdla_top_nvdla_core2cvsram_ar_arlen_s;
wire [2:0]       u_NV_nvdla_top_nvdla_core2cvsram_ar_arsize_s;
wire [1:0]       u_NV_nvdla_top_nvdla_core2cvsram_ar_arburst_s;
wire             u_NV_nvdla_top_nvdla_core2cvsram_ar_arlock_s;
wire [3:0]       u_NV_nvdla_top_nvdla_core2cvsram_ar_arcache_s;
wire [2:0]       u_NV_nvdla_top_nvdla_core2cvsram_ar_arprot_s;
wire [3:0]       u_NV_nvdla_top_nvdla_core2cvsram_r_rid_s;
wire             u_NV_nvdla_top_nvdla_core2cvsram_r_rvalid_s;
wire             u_NV_nvdla_top_nvdla_core2cvsram_r_rready_s;
wire [255:0]     u_NV_nvdla_top_nvdla_core2cvsram_r_rdata_s;
wire [1:0]       u_NV_nvdla_top_nvdla_core2cvsram_r_rresp_s;
wire             u_NV_nvdla_top_nvdla_core2cvsram_r_rlast_s;

wire [10:0]      u_uncore_top_AWID_AXI_CORE_MST_s;
wire             u_uncore_top_AWVALID_AXI_CORE_MST_s;
wire             u_uncore_top_AWREADY_AXI_CORE_MST_s;
wire [31:0]      u_uncore_top_AWADDR_AXI_CORE_MST_s;
wire [7:0]       u_uncore_top_AWLEN_AXI_CORE_MST_s;
wire [2:0]       u_uncore_top_AWSIZE_AXI_CORE_MST_s;
wire [1:0]       u_uncore_top_AWBURST_AXI_CORE_MST_s;
wire             u_uncore_top_AWLOCK_AXI_CORE_MST_s;
wire [3:0]       u_uncore_top_AWCACHE_AXI_CORE_MST_s;
wire [2:0]       u_uncore_top_AWPROT_AXI_CORE_MST_s;
wire             u_uncore_top_WVALID_AXI_CORE_MST_s;
wire             u_uncore_top_WREADY_AXI_CORE_MST_s;
wire             u_uncore_top_WLAST_AXI_CORE_MST_s;
wire [31:0]      u_uncore_top_WDATA_AXI_CORE_MST_s;
wire [3:0]       u_uncore_top_WSTRB_AXI_CORE_MST_s;
wire [10:0]      u_uncore_top_BID_AXI_CORE_MST_s;
wire             u_uncore_top_BVALID_AXI_CORE_MST_s;
wire             u_uncore_top_BREADY_AXI_CORE_MST_s;
wire [1:0]       u_uncore_top_BRESP_AXI_CORE_MST_s;
wire [10:0]      u_uncore_top_ARID_AXI_CORE_MST_s;
wire             u_uncore_top_ARVALID_AXI_CORE_MST_s;
wire             u_uncore_top_ARREADY_AXI_CORE_MST_s;
wire [31:0]      u_uncore_top_ARADDR_AXI_CORE_MST_s;
wire [7:0]       u_uncore_top_ARLEN_AXI_CORE_MST_s;
wire [2:0]       u_uncore_top_ARSIZE_AXI_CORE_MST_s;
wire [1:0]       u_uncore_top_ARBURST_AXI_CORE_MST_s;
wire             u_uncore_top_ARLOCK_AXI_CORE_MST_s;
wire [3:0]       u_uncore_top_ARCACHE_AXI_CORE_MST_s;
wire [2:0]       u_uncore_top_ARPROT_AXI_CORE_MST_s;
wire [10:0]      u_uncore_top_RID_AXI_CORE_MST_s;
wire             u_uncore_top_RVALID_AXI_CORE_MST_s;
wire             u_uncore_top_RREADY_AXI_CORE_MST_s;
wire [31:0]      u_uncore_top_RDATA_AXI_CORE_MST_s;
wire [1:0]       u_uncore_top_RRESP_AXI_CORE_MST_s;
wire             u_uncore_top_RLAST_AXI_CORE_MST_s;

wire             u_uncore_top_timer0_int_ovf_s;
wire             u_uncore_top_timer0_int_cmp_s;
wire             u_uncore_top_timer1_int_ovf_s;
wire             u_uncore_top_timer1_int_cmp_s;
wire             u_uncore_top_scu_int_s;
wire             u_uncore_top_sw_int0_s;
wire             u_uncore_top_sw_int1_s;
wire             u_uncore_top_uart_int_s;
wire             u_NV_nvdla_top_nvdla_intr_s;


// input assign
assign u_uncore_top_riscv_clk_s = u_uncore_top_riscv_clk_i;
assign u_uncore_top_riscv_core_clk_s = u_uncore_top_riscv_core_clk_i;
assign u_uncore_top_riscv_rst_s = u_uncore_top_riscv_rst_i;
assign u_uncore_top_riscv_debug_clk_s = u_uncore_top_riscv_debug_clk_i;
assign u_uncore_top_riscv_debug_rst_s = u_uncore_top_riscv_debug_rst_i;
assign u_uncore_top_riscv_rtc_toggle_s = u_uncore_top_riscv_rtc_toggle_i;
assign u_uncore_top_dla_csb_clk_s = u_uncore_top_dla_csb_clk_i;
assign u_uncore_top_dla_core_clk_s = u_uncore_top_dla_core_clk_i;
assign u_uncore_top_mac_rst_n_s = u_uncore_top_mac_rst_n_i;
assign u_uncore_top_per_clk_s = u_uncore_top_per_clk_i;
assign u_uncore_top_core_nic_rst_n_s = u_uncore_top_core_nic_rst_n_i;
assign u_uncore_top_dma_clk_s = u_uncore_top_dma_clk_i;
assign u_uncore_top_dma_rst_n_s = u_uncore_top_dma_rst_n_i;
assign u_soc_top_PCIE_EP_REFCLK_n_s = u_soc_top_PCIE_EP_REFCLK_n_i;
assign u_soc_top_PCIE_EP_REFCLK_p_s = u_soc_top_PCIE_EP_REFCLK_p_i;
assign u_soc_top_PCIE_EP_nPRESET_s = u_soc_top_PCIE_EP_nPRESET_i;
assign u_soc_top_DDR4_REF_CLK_n_s = u_soc_top_DDR4_REF_CLK_n_i;
assign u_soc_top_DDR4_REF_CLK_p_s = u_soc_top_DDR4_REF_CLK_p_i;
assign u_uncore_top_ddr_rst_s = u_uncore_top_ddr_rst_i;

assign u_soc_top_PCIE_EP_EXP_RX_n_s = u_soc_top_PCIE_EP_EXP_RX_n_i;
assign u_soc_top_PCIE_EP_EXP_RX_p_s = u_soc_top_PCIE_EP_EXP_RX_p_i;


// output assign
assign u_SiFive_CoreIPSubsystem_debug_systemjtag_jtag_TDO_data_o = u_SiFive_CoreIPSubsystem_debug_systemjtag_jtag_TDO_data_s;
assign u_xdma_0_top_axi_aresetn_o = user_rst & u_xdma_0_top_axi_aresetn_s;
assign u_xdma_0_top_user_lnk_up_o = u_xdma_0_top_user_lnk_up_s;
assign u_xdma_0_top_pci_exp_txn_o = u_xdma_0_top_pci_exp_txn_s;
assign u_xdma_0_top_pci_exp_txp_o = u_xdma_0_top_pci_exp_txp_s;
assign u_ddr4_0_top_c0_ddr4_act_n_o = u_ddr4_0_top_c0_ddr4_act_n_s;
assign u_ddr4_0_top_c0_ddr4_adr_o = u_ddr4_0_top_c0_ddr4_adr_s;
assign u_ddr4_0_top_c0_ddr4_ba_o = u_ddr4_0_top_c0_ddr4_ba_s;
assign u_ddr4_0_top_c0_ddr4_bg_o = u_ddr4_0_top_c0_ddr4_bg_s;
assign u_ddr4_0_top_c0_ddr4_ck_c_o = u_ddr4_0_top_c0_ddr4_ck_c_s;
assign u_ddr4_0_top_c0_ddr4_ck_t_o = u_ddr4_0_top_c0_ddr4_ck_t_s;
assign u_ddr4_0_top_c0_ddr4_cke_o = u_ddr4_0_top_c0_ddr4_cke_s;
assign u_ddr4_0_top_c0_ddr4_cs_n_o = u_ddr4_0_top_c0_ddr4_cs_n_s;
assign u_ddr4_0_top_c0_ddr4_odt_o = u_ddr4_0_top_c0_ddr4_odt_s;
assign u_ddr4_0_top_c0_ddr4_reset_n_o = u_ddr4_0_top_c0_ddr4_reset_n_s;
assign u_ddr4_0_top_c0_init_calib_complete_o = u_ddr4_0_top_c0_init_calib_complete_s;

// internal assign
assign u_uncore_top_AWID_AXI_CORE_MST_o = u_uncore_top_AWID_AXI_CORE_MST_s;
assign u_uncore_top_AWVALID_AXI_CORE_MST_o = u_uncore_top_AWVALID_AXI_CORE_MST_s;
assign u_uncore_top_AWREADY_AXI_CORE_MST_s = u_uncore_top_AWREADY_AXI_CORE_MST_i;
assign u_uncore_top_AWADDR_AXI_CORE_MST_o = u_uncore_top_AWADDR_AXI_CORE_MST_s;
assign u_uncore_top_AWLEN_AXI_CORE_MST_o = u_uncore_top_AWLEN_AXI_CORE_MST_s;
assign u_uncore_top_AWSIZE_AXI_CORE_MST_o = u_uncore_top_AWSIZE_AXI_CORE_MST_s;
assign u_uncore_top_AWBURST_AXI_CORE_MST_o = u_uncore_top_AWBURST_AXI_CORE_MST_s;
assign u_uncore_top_AWLOCK_AXI_CORE_MST_o = u_uncore_top_AWLOCK_AXI_CORE_MST_s;
assign u_uncore_top_AWCACHE_AXI_CORE_MST_o = u_uncore_top_AWCACHE_AXI_CORE_MST_s;
assign u_uncore_top_AWPROT_AXI_CORE_MST_o = u_uncore_top_AWPROT_AXI_CORE_MST_s;
assign u_uncore_top_WVALID_AXI_CORE_MST_o = u_uncore_top_WVALID_AXI_CORE_MST_s;
assign u_uncore_top_WREADY_AXI_CORE_MST_s = u_uncore_top_WREADY_AXI_CORE_MST_i;
assign u_uncore_top_WLAST_AXI_CORE_MST_o = u_uncore_top_WLAST_AXI_CORE_MST_s;
assign u_uncore_top_WDATA_AXI_CORE_MST_o = u_uncore_top_WDATA_AXI_CORE_MST_s;
assign u_uncore_top_WSTRB_AXI_CORE_MST_o = u_uncore_top_WSTRB_AXI_CORE_MST_s;
assign u_uncore_top_BID_AXI_CORE_MST_s = u_uncore_top_BID_AXI_CORE_MST_i;
assign u_uncore_top_BVALID_AXI_CORE_MST_s = u_uncore_top_BVALID_AXI_CORE_MST_i;
assign u_uncore_top_BREADY_AXI_CORE_MST_o = u_uncore_top_BREADY_AXI_CORE_MST_s;
assign u_uncore_top_BRESP_AXI_CORE_MST_s = u_uncore_top_BRESP_AXI_CORE_MST_i;
assign u_uncore_top_ARID_AXI_CORE_MST_o = u_uncore_top_ARID_AXI_CORE_MST_s;
assign u_uncore_top_ARVALID_AXI_CORE_MST_o = u_uncore_top_ARVALID_AXI_CORE_MST_s;
assign u_uncore_top_ARREADY_AXI_CORE_MST_s = u_uncore_top_ARREADY_AXI_CORE_MST_i;
assign u_uncore_top_ARADDR_AXI_CORE_MST_o = u_uncore_top_ARADDR_AXI_CORE_MST_s;
assign u_uncore_top_ARLEN_AXI_CORE_MST_o = u_uncore_top_ARLEN_AXI_CORE_MST_s;
assign u_uncore_top_ARSIZE_AXI_CORE_MST_o = u_uncore_top_ARSIZE_AXI_CORE_MST_s;
assign u_uncore_top_ARBURST_AXI_CORE_MST_o = u_uncore_top_ARBURST_AXI_CORE_MST_s;
assign u_uncore_top_ARLOCK_AXI_CORE_MST_o = u_uncore_top_ARLOCK_AXI_CORE_MST_s;
assign u_uncore_top_ARCACHE_AXI_CORE_MST_o = u_uncore_top_ARCACHE_AXI_CORE_MST_s;
assign u_uncore_top_ARPROT_AXI_CORE_MST_o = u_uncore_top_ARPROT_AXI_CORE_MST_s;
assign u_uncore_top_RID_AXI_CORE_MST_s = u_uncore_top_RID_AXI_CORE_MST_i;
assign u_uncore_top_RVALID_AXI_CORE_MST_s = u_uncore_top_RVALID_AXI_CORE_MST_i;
assign u_uncore_top_RREADY_AXI_CORE_MST_o = u_uncore_top_RREADY_AXI_CORE_MST_s;
assign u_uncore_top_RDATA_AXI_CORE_MST_s = u_uncore_top_RDATA_AXI_CORE_MST_i;
assign u_uncore_top_RRESP_AXI_CORE_MST_s = u_uncore_top_RRESP_AXI_CORE_MST_i;
assign u_uncore_top_RLAST_AXI_CORE_MST_s = u_uncore_top_RLAST_AXI_CORE_MST_i;

assign u_uncore_top_timer0_int_ovf_s = u_uncore_top_timer0_int_ovf_i;
assign u_uncore_top_timer0_int_cmp_s = u_uncore_top_timer0_int_cmp_i;
assign u_uncore_top_timer1_int_ovf_s = u_uncore_top_timer1_int_ovf_i;
assign u_uncore_top_timer1_int_cmp_s = u_uncore_top_timer1_int_cmp_i;
assign u_uncore_top_scu_int_s = u_uncore_top_scu_int_i;
assign u_uncore_top_sw_int0_s = u_uncore_top_sw_int0_i;
assign u_uncore_top_sw_int1_s = u_uncore_top_sw_int1_i;
assign u_uncore_top_uart_int_s = u_uncore_top_uart_int_i;


//u_riscv_subsys_top instance
riscv_subsys_top u_riscv_subsys_top(
    .u_uncore_top_riscv_clk_i(u_uncore_top_riscv_clk_s),
    .u_uncore_top_riscv_core_clk_i(u_uncore_top_riscv_core_clk_s),
    .u_uncore_top_riscv_rst_i(u_uncore_top_riscv_rst_s),
    .u_uncore_top_riscv_debug_clk_i(u_uncore_top_riscv_debug_clk_s),
    .u_uncore_top_riscv_debug_rst_i(u_uncore_top_riscv_debug_rst_s),
    .u_uncore_top_riscv_rtc_toggle_i(u_uncore_top_riscv_rtc_toggle_s),
    .u_uncore_top_per_clk_i(u_uncore_top_per_clk_s),
    .u_uncore_top_core_nic_rst_n_i(u_uncore_top_core_nic_rst_n_s),
    .u_uncore_top_dma_clk_i(u_uncore_top_dma_clk_s),
    .u_uncore_top_dma_rst_n_i(u_uncore_top_dma_rst_n_s),
    .u_xdma_0_top_axi_aclk_i(u_xdma_0_top_axi_aclk_s),
    .u_xdma_0_top_axi_aresetn_i(u_xdma_0_top_axi_aresetn_s),
    .u_ddr4_0_top_c0_ddr4_ui_clk_i(u_ddr4_0_top_c0_ddr4_ui_clk_s),
    .por_rstn_sync(por_rstn_sync),
    .u_soc_top_TCK_i(u_soc_top_TCK_s),
    .u_soc_top_TRST_n_i(u_soc_top_TRST_n_s),
    .u_tdi_rmux_z_i(u_tdi_rmux_z_s),
    .u_tms_rmux_z_i(u_tms_rmux_z_s),
    .debug_systemjtag_jtag_TDO_driven(debug_systemjtag_jtag_TDO_driven),
    .u_SiFive_CoreIPSubsystem_debug_systemjtag_jtag_TDO_data_o(u_SiFive_CoreIPSubsystem_debug_systemjtag_jtag_TDO_data_s),
    .riscv_debug_dmactive(riscv_debug_dmactive),
    .riscv_debug_dmactiveack(riscv_debug_dmactiveack),
    .u_xdma_0_top_s_axil_awvalid_o(u_xdma_0_top_s_axil_awvalid_s),
    .u_xdma_0_top_s_axil_awready_i(u_xdma_0_top_s_axil_awready_s),
    .u_xdma_0_top_s_axil_awaddr_o(u_xdma_0_top_s_axil_awaddr_s),
    .u_xdma_0_top_s_axil_awprot_o(u_xdma_0_top_s_axil_awprot_s),
    .u_xdma_0_top_s_axil_wvalid_o(u_xdma_0_top_s_axil_wvalid_s),
    .u_xdma_0_top_s_axil_wready_i(u_xdma_0_top_s_axil_wready_s),
    .u_xdma_0_top_s_axil_wdata_o(u_xdma_0_top_s_axil_wdata_s),
    .u_xdma_0_top_s_axil_wstrb_o(u_xdma_0_top_s_axil_wstrb_s),
    .u_xdma_0_top_s_axil_bvalid_i(u_xdma_0_top_s_axil_bvalid_s),
    .u_xdma_0_top_s_axil_bready_o(u_xdma_0_top_s_axil_bready_s),
    .u_xdma_0_top_s_axil_bresp_i(u_xdma_0_top_s_axil_bresp_s),
    .u_xdma_0_top_s_axil_arvalid_o(u_xdma_0_top_s_axil_arvalid_s),
    .u_xdma_0_top_s_axil_arready_i(u_xdma_0_top_s_axil_arready_s),
    .u_xdma_0_top_s_axil_araddr_o(u_xdma_0_top_s_axil_araddr_s),
    .u_xdma_0_top_s_axil_arprot_o(u_xdma_0_top_s_axil_arprot_s),
    .u_xdma_0_top_s_axil_rvalid_i(u_xdma_0_top_s_axil_rvalid_s),
    .u_xdma_0_top_s_axil_rready_o(u_xdma_0_top_s_axil_rready_s),
    .u_xdma_0_top_s_axil_rdata_i(u_xdma_0_top_s_axil_rdata_s),
    .u_xdma_0_top_s_axil_rresp_i(u_xdma_0_top_s_axil_rresp_s),
    .u_xdma_0_top_m_axi_awid_i(u_xdma_0_top_m_axi_awid_s),
    .u_xdma_0_top_m_axi_awvalid_i(u_xdma_0_top_m_axi_awvalid_s),
    .u_xdma_0_top_m_axi_awready_o(u_xdma_0_top_m_axi_awready_s),
    .u_xdma_0_top_m_axi_awaddr_i(u_xdma_0_top_m_axi_awaddr_s),
    .u_xdma_0_top_m_axi_awlen_i(u_xdma_0_top_m_axi_awlen_s),
    .u_xdma_0_top_m_axi_awsize_i(u_xdma_0_top_m_axi_awsize_s),
    .u_xdma_0_top_m_axi_awburst_i(u_xdma_0_top_m_axi_awburst_s),
    .u_xdma_0_top_m_axi_awlock_i(u_xdma_0_top_m_axi_awlock_s),
    .u_xdma_0_top_m_axi_awcache_i(u_xdma_0_top_m_axi_awcache_s),
    .u_xdma_0_top_m_axi_awprot_i(u_xdma_0_top_m_axi_awprot_s),
    .u_xdma_0_top_m_axi_wvalid_i(u_xdma_0_top_m_axi_wvalid_s),
    .u_xdma_0_top_m_axi_wready_o(u_xdma_0_top_m_axi_wready_s),
    .u_xdma_0_top_m_axi_wlast_i(u_xdma_0_top_m_axi_wlast_s),
    .u_xdma_0_top_m_axi_wdata_i(u_xdma_0_top_m_axi_wdata_s),
    .u_xdma_0_top_m_axi_wstrb_i(u_xdma_0_top_m_axi_wstrb_s),
    .u_xdma_0_top_m_axi_bid_o(u_xdma_0_top_m_axi_bid_s),
    .u_xdma_0_top_m_axi_bvalid_o(u_xdma_0_top_m_axi_bvalid_s),
    .u_xdma_0_top_m_axi_bready_i(u_xdma_0_top_m_axi_bready_s),
    .u_xdma_0_top_m_axi_bresp_o(u_xdma_0_top_m_axi_bresp_s),
    .u_xdma_0_top_m_axi_arid_i(u_xdma_0_top_m_axi_arid_s),
    .u_xdma_0_top_m_axi_arvalid_i(u_xdma_0_top_m_axi_arvalid_s),
    .u_xdma_0_top_m_axi_arready_o(u_xdma_0_top_m_axi_arready_s),
    .u_xdma_0_top_m_axi_araddr_i(u_xdma_0_top_m_axi_araddr_s),
    .u_xdma_0_top_m_axi_arlen_i(u_xdma_0_top_m_axi_arlen_s),
    .u_xdma_0_top_m_axi_arsize_i(u_xdma_0_top_m_axi_arsize_s),
    .u_xdma_0_top_m_axi_arburst_i(u_xdma_0_top_m_axi_arburst_s),
    .u_xdma_0_top_m_axi_arlock_i(u_xdma_0_top_m_axi_arlock_s),
    .u_xdma_0_top_m_axi_arcache_i(u_xdma_0_top_m_axi_arcache_s),
    .u_xdma_0_top_m_axi_arprot_i(u_xdma_0_top_m_axi_arprot_s),
    .u_xdma_0_top_m_axi_rid_o(u_xdma_0_top_m_axi_rid_s),
    .u_xdma_0_top_m_axi_rvalid_o(u_xdma_0_top_m_axi_rvalid_s),
    .u_xdma_0_top_m_axi_rready_i(u_xdma_0_top_m_axi_rready_s),
    .u_xdma_0_top_m_axi_rdata_o(u_xdma_0_top_m_axi_rdata_s),
    .u_xdma_0_top_m_axi_rresp_o(u_xdma_0_top_m_axi_rresp_s),
    .u_xdma_0_top_m_axi_rlast_o(u_xdma_0_top_m_axi_rlast_s),
    .u_xdma_0_top_m_axil_awvalid_i(u_xdma_0_top_m_axil_awvalid_s),
    .u_xdma_0_top_m_axil_awready_o(u_xdma_0_top_m_axil_awready_s),
    .u_xdma_0_top_m_axil_awaddr_i(u_xdma_0_top_m_axil_awaddr_s),
    .u_xdma_0_top_m_axil_awprot_i(u_xdma_0_top_m_axil_awprot_s),
    .u_xdma_0_top_m_axil_wvalid_i(u_xdma_0_top_m_axil_wvalid_s),
    .u_xdma_0_top_m_axil_wready_o(u_xdma_0_top_m_axil_wready_s),
    .u_xdma_0_top_m_axil_wdata_i(u_xdma_0_top_m_axil_wdata_s),
    .u_xdma_0_top_m_axil_wstrb_i(u_xdma_0_top_m_axil_wstrb_s),
    .u_xdma_0_top_m_axil_bvalid_o(u_xdma_0_top_m_axil_bvalid_s),
    .u_xdma_0_top_m_axil_bready_i(u_xdma_0_top_m_axil_bready_s),
    .u_xdma_0_top_m_axil_bresp_o(u_xdma_0_top_m_axil_bresp_s),
    .u_xdma_0_top_m_axil_arvalid_i(u_xdma_0_top_m_axil_arvalid_s),
    .u_xdma_0_top_m_axil_arready_o(u_xdma_0_top_m_axil_arready_s),
    .u_xdma_0_top_m_axil_araddr_i(u_xdma_0_top_m_axil_araddr_s),
    .u_xdma_0_top_m_axil_arprot_i(u_xdma_0_top_m_axil_arprot_s),
    .u_xdma_0_top_m_axil_rvalid_o(u_xdma_0_top_m_axil_rvalid_s),
    .u_xdma_0_top_m_axil_rready_i(u_xdma_0_top_m_axil_rready_s),
    .u_xdma_0_top_m_axil_rdata_o(u_xdma_0_top_m_axil_rdata_s),
    .u_xdma_0_top_m_axil_rresp_o(u_xdma_0_top_m_axil_rresp_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_awid_o(u_ddr4_0_top_c0_ddr4_s_axi_awid_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_awvalid_o(u_ddr4_0_top_c0_ddr4_s_axi_awvalid_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_awready_i(u_ddr4_0_top_c0_ddr4_s_axi_awready_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_awaddr_o(u_ddr4_0_top_c0_ddr4_s_axi_awaddr_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_awlen_o(u_ddr4_0_top_c0_ddr4_s_axi_awlen_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_awsize_o(u_ddr4_0_top_c0_ddr4_s_axi_awsize_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_awburst_o(u_ddr4_0_top_c0_ddr4_s_axi_awburst_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_awlock_o(u_ddr4_0_top_c0_ddr4_s_axi_awlock_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_awcache_o(u_ddr4_0_top_c0_ddr4_s_axi_awcache_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_awprot_o(u_ddr4_0_top_c0_ddr4_s_axi_awprot_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_wvalid_o(u_ddr4_0_top_c0_ddr4_s_axi_wvalid_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_wready_i(u_ddr4_0_top_c0_ddr4_s_axi_wready_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_wlast_o(u_ddr4_0_top_c0_ddr4_s_axi_wlast_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_wdata_o(u_ddr4_0_top_c0_ddr4_s_axi_wdata_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_wstrb_o(u_ddr4_0_top_c0_ddr4_s_axi_wstrb_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_bid_i(u_ddr4_0_top_c0_ddr4_s_axi_bid_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_bvalid_i(u_ddr4_0_top_c0_ddr4_s_axi_bvalid_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_bready_o(u_ddr4_0_top_c0_ddr4_s_axi_bready_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_bresp_i(u_ddr4_0_top_c0_ddr4_s_axi_bresp_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_arid_o(u_ddr4_0_top_c0_ddr4_s_axi_arid_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_arvalid_o(u_ddr4_0_top_c0_ddr4_s_axi_arvalid_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_arready_i(u_ddr4_0_top_c0_ddr4_s_axi_arready_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_araddr_o(u_ddr4_0_top_c0_ddr4_s_axi_araddr_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_arlen_o(u_ddr4_0_top_c0_ddr4_s_axi_arlen_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_arsize_o(u_ddr4_0_top_c0_ddr4_s_axi_arsize_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_arburst_o(u_ddr4_0_top_c0_ddr4_s_axi_arburst_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_arlock_o(u_ddr4_0_top_c0_ddr4_s_axi_arlock_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_arcache_o(u_ddr4_0_top_c0_ddr4_s_axi_arcache_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_arprot_o(u_ddr4_0_top_c0_ddr4_s_axi_arprot_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_rid_i(u_ddr4_0_top_c0_ddr4_s_axi_rid_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_rvalid_i(u_ddr4_0_top_c0_ddr4_s_axi_rvalid_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_rready_o(u_ddr4_0_top_c0_ddr4_s_axi_rready_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_rdata_i(u_ddr4_0_top_c0_ddr4_s_axi_rdata_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_rresp_i(u_ddr4_0_top_c0_ddr4_s_axi_rresp_s),
    .u_ddr4_0_top_c0_ddr4_s_axi_rlast_i(u_ddr4_0_top_c0_ddr4_s_axi_rlast_s),
    .u_NV_nvdla_top_pselX_o(u_NV_nvdla_top_pselX_s),
    .u_NV_nvdla_top_penable_o(u_NV_nvdla_top_penable_s),
    .u_NV_nvdla_top_pwrite_o(u_NV_nvdla_top_pwrite_s),
    .u_NV_nvdla_top_paddr_o(u_NV_nvdla_top_paddr_s),
    .u_NV_nvdla_top_pwdata_o(u_NV_nvdla_top_pwdata_s),
    .u_NV_nvdla_top_prdata_i(u_NV_nvdla_top_prdata_s),
    .u_NV_nvdla_top_pready_i(u_NV_nvdla_top_pready_s),
    .u_NV_nvdla_top_pslverr_i(u_NV_nvdla_top_pslverr_s),
    .u_NV_nvdla_top_nvdla_core2dbb_aw_awid_i(u_NV_nvdla_top_nvdla_core2dbb_aw_awid_s),
    .u_NV_nvdla_top_nvdla_core2dbb_aw_awvalid_i(u_NV_nvdla_top_nvdla_core2dbb_aw_awvalid_s),
    .u_NV_nvdla_top_nvdla_core2dbb_aw_awready_o(u_NV_nvdla_top_nvdla_core2dbb_aw_awready_s),
    .u_NV_nvdla_top_nvdla_core2dbb_aw_awaddr_i(u_NV_nvdla_top_nvdla_core2dbb_aw_awaddr_s),
    .u_NV_nvdla_top_nvdla_core2dbb_aw_awlen_i(u_NV_nvdla_top_nvdla_core2dbb_aw_awlen_s),
    .u_NV_nvdla_top_nvdla_core2dbb_aw_awsize_i(u_NV_nvdla_top_nvdla_core2dbb_aw_awsize_s),
    .u_NV_nvdla_top_nvdla_core2dbb_aw_awburst_i(u_NV_nvdla_top_nvdla_core2dbb_aw_awburst_s),
    .u_NV_nvdla_top_nvdla_core2dbb_aw_awlock_i(u_NV_nvdla_top_nvdla_core2dbb_aw_awlock_s),
    .u_NV_nvdla_top_nvdla_core2dbb_aw_awcache_i(u_NV_nvdla_top_nvdla_core2dbb_aw_awcache_s),
    .u_NV_nvdla_top_nvdla_core2dbb_aw_awprot_i(u_NV_nvdla_top_nvdla_core2dbb_aw_awprot_s),
    .u_NV_nvdla_top_nvdla_core2dbb_w_wvalid_i(u_NV_nvdla_top_nvdla_core2dbb_w_wvalid_s),
    .u_NV_nvdla_top_nvdla_core2dbb_w_wready_o(u_NV_nvdla_top_nvdla_core2dbb_w_wready_s),
    .u_NV_nvdla_top_nvdla_core2dbb_w_wlast_i(u_NV_nvdla_top_nvdla_core2dbb_w_wlast_s),
    .u_NV_nvdla_top_nvdla_core2dbb_w_wdata_i(u_NV_nvdla_top_nvdla_core2dbb_w_wdata_s),
    .u_NV_nvdla_top_nvdla_core2dbb_w_wstrb_i(u_NV_nvdla_top_nvdla_core2dbb_w_wstrb_s),
    .u_NV_nvdla_top_nvdla_core2dbb_b_bid_o(u_NV_nvdla_top_nvdla_core2dbb_b_bid_s),
    .u_NV_nvdla_top_nvdla_core2dbb_b_bvalid_o(u_NV_nvdla_top_nvdla_core2dbb_b_bvalid_s),
    .u_NV_nvdla_top_nvdla_core2dbb_b_bready_i(u_NV_nvdla_top_nvdla_core2dbb_b_bready_s),
    .u_NV_nvdla_top_nvdla_core2dbb_b_bresp_o(u_NV_nvdla_top_nvdla_core2dbb_b_bresp_s),
    .u_NV_nvdla_top_nvdla_core2dbb_ar_arid_i(u_NV_nvdla_top_nvdla_core2dbb_ar_arid_s),
    .u_NV_nvdla_top_nvdla_core2dbb_ar_arvalid_i(u_NV_nvdla_top_nvdla_core2dbb_ar_arvalid_s),
    .u_NV_nvdla_top_nvdla_core2dbb_ar_arready_o(u_NV_nvdla_top_nvdla_core2dbb_ar_arready_s),
    .u_NV_nvdla_top_nvdla_core2dbb_ar_araddr_i(u_NV_nvdla_top_nvdla_core2dbb_ar_araddr_s),
    .u_NV_nvdla_top_nvdla_core2dbb_ar_arlen_i(u_NV_nvdla_top_nvdla_core2dbb_ar_arlen_s),
    .u_NV_nvdla_top_nvdla_core2dbb_ar_arsize_i(u_NV_nvdla_top_nvdla_core2dbb_ar_arsize_s),
    .u_NV_nvdla_top_nvdla_core2dbb_ar_arburst_i(u_NV_nvdla_top_nvdla_core2dbb_ar_arburst_s),
    .u_NV_nvdla_top_nvdla_core2dbb_ar_arlock_i(u_NV_nvdla_top_nvdla_core2dbb_ar_arlock_s),
    .u_NV_nvdla_top_nvdla_core2dbb_ar_arcache_i(u_NV_nvdla_top_nvdla_core2dbb_ar_arcache_s),
    .u_NV_nvdla_top_nvdla_core2dbb_ar_arprot_i(u_NV_nvdla_top_nvdla_core2dbb_ar_arprot_s),
    .u_NV_nvdla_top_nvdla_core2dbb_r_rid_o(u_NV_nvdla_top_nvdla_core2dbb_r_rid_s),
    .u_NV_nvdla_top_nvdla_core2dbb_r_rvalid_o(u_NV_nvdla_top_nvdla_core2dbb_r_rvalid_s),
    .u_NV_nvdla_top_nvdla_core2dbb_r_rready_i(u_NV_nvdla_top_nvdla_core2dbb_r_rready_s),
    .u_NV_nvdla_top_nvdla_core2dbb_r_rdata_o(u_NV_nvdla_top_nvdla_core2dbb_r_rdata_s),
    .u_NV_nvdla_top_nvdla_core2dbb_r_rresp_o(u_NV_nvdla_top_nvdla_core2dbb_r_rresp_s),
    .u_NV_nvdla_top_nvdla_core2dbb_r_rlast_o(u_NV_nvdla_top_nvdla_core2dbb_r_rlast_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_aw_awid_i(u_NV_nvdla_top_nvdla_core2cvsram_aw_awid_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_aw_awvalid_i(u_NV_nvdla_top_nvdla_core2cvsram_aw_awvalid_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_aw_awready_o(u_NV_nvdla_top_nvdla_core2cvsram_aw_awready_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_aw_awaddr_i(u_NV_nvdla_top_nvdla_core2cvsram_aw_awaddr_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_aw_awlen_i(u_NV_nvdla_top_nvdla_core2cvsram_aw_awlen_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_aw_awsize_i(u_NV_nvdla_top_nvdla_core2cvsram_aw_awsize_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_aw_awburst_i(u_NV_nvdla_top_nvdla_core2cvsram_aw_awburst_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_aw_awlock_i(u_NV_nvdla_top_nvdla_core2cvsram_aw_awlock_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_aw_awcache_i(u_NV_nvdla_top_nvdla_core2cvsram_aw_awcache_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_aw_awprot_i(u_NV_nvdla_top_nvdla_core2cvsram_aw_awprot_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_w_wvalid_i(u_NV_nvdla_top_nvdla_core2cvsram_w_wvalid_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_w_wready_o(u_NV_nvdla_top_nvdla_core2cvsram_w_wready_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_w_wlast_i(u_NV_nvdla_top_nvdla_core2cvsram_w_wlast_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_w_wdata_i(u_NV_nvdla_top_nvdla_core2cvsram_w_wdata_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_w_wstrb_i(u_NV_nvdla_top_nvdla_core2cvsram_w_wstrb_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_b_bid_o(u_NV_nvdla_top_nvdla_core2cvsram_b_bid_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_b_bvalid_o(u_NV_nvdla_top_nvdla_core2cvsram_b_bvalid_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_b_bready_i(u_NV_nvdla_top_nvdla_core2cvsram_b_bready_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_b_bresp_o(u_NV_nvdla_top_nvdla_core2cvsram_b_bresp_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_ar_arid_i(u_NV_nvdla_top_nvdla_core2cvsram_ar_arid_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_ar_arvalid_i(u_NV_nvdla_top_nvdla_core2cvsram_ar_arvalid_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_ar_arready_o(u_NV_nvdla_top_nvdla_core2cvsram_ar_arready_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_ar_araddr_i(u_NV_nvdla_top_nvdla_core2cvsram_ar_araddr_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_ar_arlen_i(u_NV_nvdla_top_nvdla_core2cvsram_ar_arlen_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_ar_arsize_i(u_NV_nvdla_top_nvdla_core2cvsram_ar_arsize_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_ar_arburst_i(u_NV_nvdla_top_nvdla_core2cvsram_ar_arburst_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_ar_arlock_i(u_NV_nvdla_top_nvdla_core2cvsram_ar_arlock_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_ar_arcache_i(u_NV_nvdla_top_nvdla_core2cvsram_ar_arcache_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_ar_arprot_i(u_NV_nvdla_top_nvdla_core2cvsram_ar_arprot_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_r_rid_o(u_NV_nvdla_top_nvdla_core2cvsram_r_rid_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_r_rvalid_o(u_NV_nvdla_top_nvdla_core2cvsram_r_rvalid_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_r_rready_i(u_NV_nvdla_top_nvdla_core2cvsram_r_rready_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_r_rdata_o(u_NV_nvdla_top_nvdla_core2cvsram_r_rdata_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_r_rresp_o(u_NV_nvdla_top_nvdla_core2cvsram_r_rresp_s),
    .u_NV_nvdla_top_nvdla_core2cvsram_r_rlast_o(u_NV_nvdla_top_nvdla_core2cvsram_r_rlast_s),
    .u_uncore_top_AWID_AXI_CORE_MST_o(u_uncore_top_AWID_AXI_CORE_MST_s),
    .u_uncore_top_AWVALID_AXI_CORE_MST_o(u_uncore_top_AWVALID_AXI_CORE_MST_s),
    .u_uncore_top_AWREADY_AXI_CORE_MST_i(u_uncore_top_AWREADY_AXI_CORE_MST_s),
    .u_uncore_top_AWADDR_AXI_CORE_MST_o(u_uncore_top_AWADDR_AXI_CORE_MST_s),
    .u_uncore_top_AWLEN_AXI_CORE_MST_o(u_uncore_top_AWLEN_AXI_CORE_MST_s),
    .u_uncore_top_AWSIZE_AXI_CORE_MST_o(u_uncore_top_AWSIZE_AXI_CORE_MST_s),
    .u_uncore_top_AWBURST_AXI_CORE_MST_o(u_uncore_top_AWBURST_AXI_CORE_MST_s),
    .u_uncore_top_AWLOCK_AXI_CORE_MST_o(u_uncore_top_AWLOCK_AXI_CORE_MST_s),
    .u_uncore_top_AWCACHE_AXI_CORE_MST_o(u_uncore_top_AWCACHE_AXI_CORE_MST_s),
    .u_uncore_top_AWPROT_AXI_CORE_MST_o(u_uncore_top_AWPROT_AXI_CORE_MST_s),
    .u_uncore_top_WVALID_AXI_CORE_MST_o(u_uncore_top_WVALID_AXI_CORE_MST_s),
    .u_uncore_top_WREADY_AXI_CORE_MST_i(u_uncore_top_WREADY_AXI_CORE_MST_s),
    .u_uncore_top_WLAST_AXI_CORE_MST_o(u_uncore_top_WLAST_AXI_CORE_MST_s),
    .u_uncore_top_WDATA_AXI_CORE_MST_o(u_uncore_top_WDATA_AXI_CORE_MST_s),
    .u_uncore_top_WSTRB_AXI_CORE_MST_o(u_uncore_top_WSTRB_AXI_CORE_MST_s),
    .u_uncore_top_BID_AXI_CORE_MST_i(u_uncore_top_BID_AXI_CORE_MST_s),
    .u_uncore_top_BVALID_AXI_CORE_MST_i(u_uncore_top_BVALID_AXI_CORE_MST_s),
    .u_uncore_top_BREADY_AXI_CORE_MST_o(u_uncore_top_BREADY_AXI_CORE_MST_s),
    .u_uncore_top_BRESP_AXI_CORE_MST_i(u_uncore_top_BRESP_AXI_CORE_MST_s),
    .u_uncore_top_ARID_AXI_CORE_MST_o(u_uncore_top_ARID_AXI_CORE_MST_s),
    .u_uncore_top_ARVALID_AXI_CORE_MST_o(u_uncore_top_ARVALID_AXI_CORE_MST_s),
    .u_uncore_top_ARREADY_AXI_CORE_MST_i(u_uncore_top_ARREADY_AXI_CORE_MST_s),
    .u_uncore_top_ARADDR_AXI_CORE_MST_o(u_uncore_top_ARADDR_AXI_CORE_MST_s),
    .u_uncore_top_ARLEN_AXI_CORE_MST_o(u_uncore_top_ARLEN_AXI_CORE_MST_s),
    .u_uncore_top_ARSIZE_AXI_CORE_MST_o(u_uncore_top_ARSIZE_AXI_CORE_MST_s),
    .u_uncore_top_ARBURST_AXI_CORE_MST_o(u_uncore_top_ARBURST_AXI_CORE_MST_s),
    .u_uncore_top_ARLOCK_AXI_CORE_MST_o(u_uncore_top_ARLOCK_AXI_CORE_MST_s),
    .u_uncore_top_ARCACHE_AXI_CORE_MST_o(u_uncore_top_ARCACHE_AXI_CORE_MST_s),
    .u_uncore_top_ARPROT_AXI_CORE_MST_o(u_uncore_top_ARPROT_AXI_CORE_MST_s),
    .u_uncore_top_RID_AXI_CORE_MST_i(u_uncore_top_RID_AXI_CORE_MST_s),
    .u_uncore_top_RVALID_AXI_CORE_MST_i(u_uncore_top_RVALID_AXI_CORE_MST_s),
    .u_uncore_top_RREADY_AXI_CORE_MST_o(u_uncore_top_RREADY_AXI_CORE_MST_s),
    .u_uncore_top_RDATA_AXI_CORE_MST_i(u_uncore_top_RDATA_AXI_CORE_MST_s),
    .u_uncore_top_RRESP_AXI_CORE_MST_i(u_uncore_top_RRESP_AXI_CORE_MST_s),
    .u_uncore_top_RLAST_AXI_CORE_MST_i(u_uncore_top_RLAST_AXI_CORE_MST_s),
    .u_uncore_top_timer0_int_cmp_i(u_uncore_top_timer0_int_cmp_s),
    .u_uncore_top_timer0_int_ovf_i(u_uncore_top_timer0_int_ovf_s),
    .u_uncore_top_timer1_int_cmp_i(u_uncore_top_timer1_int_cmp_s),
    .u_uncore_top_timer1_int_ovf_i(u_uncore_top_timer1_int_ovf_s),
    .u_uncore_top_sw_int0_i(u_uncore_top_sw_int0_s),
    .u_uncore_top_sw_int1_i(u_uncore_top_sw_int1_s),
    .u_uncore_top_scu_int_i(u_uncore_top_scu_int_s),
    .u_uncore_top_uart_int_i(u_uncore_top_uart_int_s),
    .u_NV_nvdla_top_nvdla_intr_i(u_NV_nvdla_top_nvdla_intr_s)
    //input ports
    //output ports
    //inout ports
);


logic [31:0] awaddr_pcie_ep_s_lite_offset_s ;
logic [31:0] araddr_pcie_ep_s_lite_offset_s ;

assign awaddr_pcie_ep_s_lite_offset_s = u_xdma_0_top_s_axil_awaddr_s  - 32'h4000_0000     ;
assign araddr_pcie_ep_s_lite_offset_s = u_xdma_0_top_s_axil_araddr_s  - 32'h4000_0000     ;

//u_xdma_0_top instance
xdma_0 u_xdma_0_top(
    .sys_clk(u_pcie_xclk_to_single_sys_clk_s),
    .sys_clk_gt(u_pcie_xclk_to_single_sys_clk_gt_s),
    .sys_rst_n(u_soc_top_PCIE_EP_nPRESET_s),
    .axi_aclk(u_xdma_0_top_axi_aclk_s),
    .axi_aresetn(u_xdma_0_top_axi_aresetn_s),
    .s_axil_awvalid(u_xdma_0_top_s_axil_awvalid_s),
    .s_axil_awready(u_xdma_0_top_s_axil_awready_s),
    .s_axil_awaddr(awaddr_pcie_ep_s_lite_offset_s),
    .s_axil_awprot(u_xdma_0_top_s_axil_awprot_s),
    .s_axil_wvalid(u_xdma_0_top_s_axil_wvalid_s),
    .s_axil_wready(u_xdma_0_top_s_axil_wready_s),
    .s_axil_wdata(u_xdma_0_top_s_axil_wdata_s),
    .s_axil_wstrb(u_xdma_0_top_s_axil_wstrb_s),
    .s_axil_bvalid(u_xdma_0_top_s_axil_bvalid_s),
    .s_axil_bready(u_xdma_0_top_s_axil_bready_s),
    .s_axil_bresp(u_xdma_0_top_s_axil_bresp_s),
    .s_axil_arvalid(u_xdma_0_top_s_axil_arvalid_s),
    .s_axil_arready(u_xdma_0_top_s_axil_arready_s),
    .s_axil_araddr(araddr_pcie_ep_s_lite_offset_s),
    .s_axil_arprot(u_xdma_0_top_s_axil_arprot_s),
    .s_axil_rvalid(u_xdma_0_top_s_axil_rvalid_s),
    .s_axil_rready(u_xdma_0_top_s_axil_rready_s),
    .s_axil_rdata(u_xdma_0_top_s_axil_rdata_s),
    .s_axil_rresp(u_xdma_0_top_s_axil_rresp_s),
    .m_axi_awid(u_xdma_0_top_m_axi_awid_s),
    .m_axi_awvalid(u_xdma_0_top_m_axi_awvalid_s),
    .m_axi_awready(u_xdma_0_top_m_axi_awready_s),
    .m_axi_awaddr(u_xdma_0_top_m_axi_awaddr_s),
    .m_axi_awlen(u_xdma_0_top_m_axi_awlen_s),
    .m_axi_awsize(u_xdma_0_top_m_axi_awsize_s),
    .m_axi_awburst(u_xdma_0_top_m_axi_awburst_s),
    .m_axi_awlock(u_xdma_0_top_m_axi_awlock_s),
    .m_axi_awcache(u_xdma_0_top_m_axi_awcache_s),
    .m_axi_awprot(u_xdma_0_top_m_axi_awprot_s),
    .m_axi_wvalid(u_xdma_0_top_m_axi_wvalid_s),
    .m_axi_wready(u_xdma_0_top_m_axi_wready_s),
    .m_axi_wlast(u_xdma_0_top_m_axi_wlast_s),
    .m_axi_wdata(u_xdma_0_top_m_axi_wdata_s),
    .m_axi_wstrb(u_xdma_0_top_m_axi_wstrb_s),
    .m_axi_bid(u_xdma_0_top_m_axi_bid_s),
    .m_axi_bvalid(u_xdma_0_top_m_axi_bvalid_s),
    .m_axi_bready(u_xdma_0_top_m_axi_bready_s),
    .m_axi_bresp(u_xdma_0_top_m_axi_bresp_s),
    .m_axi_arid(u_xdma_0_top_m_axi_arid_s),
    .m_axi_arvalid(u_xdma_0_top_m_axi_arvalid_s),
    .m_axi_arready(u_xdma_0_top_m_axi_arready_s),
    .m_axi_araddr(u_xdma_0_top_m_axi_araddr_s),
    .m_axi_arlen(u_xdma_0_top_m_axi_arlen_s),
    .m_axi_arsize(u_xdma_0_top_m_axi_arsize_s),
    .m_axi_arburst(u_xdma_0_top_m_axi_arburst_s),
    .m_axi_arlock(u_xdma_0_top_m_axi_arlock_s),
    .m_axi_arcache(u_xdma_0_top_m_axi_arcache_s),
    .m_axi_arprot(u_xdma_0_top_m_axi_arprot_s),
    .m_axi_rid(u_xdma_0_top_m_axi_rid_s),
    .m_axi_rvalid(u_xdma_0_top_m_axi_rvalid_s),
    .m_axi_rready(u_xdma_0_top_m_axi_rready_s),
    .m_axi_rdata(u_xdma_0_top_m_axi_rdata_s),
    .m_axi_rresp(u_xdma_0_top_m_axi_rresp_s),
    .m_axi_rlast(u_xdma_0_top_m_axi_rlast_s),
    .m_axil_awvalid(u_xdma_0_top_m_axil_awvalid_s),
    .m_axil_awready(u_xdma_0_top_m_axil_awready_s),
    .m_axil_awaddr(u_xdma_0_top_m_axil_awaddr_s),
    .m_axil_awprot(u_xdma_0_top_m_axil_awprot_s),
    .m_axil_wvalid(u_xdma_0_top_m_axil_wvalid_s),
    .m_axil_wready(u_xdma_0_top_m_axil_wready_s),
    .m_axil_wdata(u_xdma_0_top_m_axil_wdata_s),
    .m_axil_wstrb(u_xdma_0_top_m_axil_wstrb_s),
    .m_axil_bvalid(u_xdma_0_top_m_axil_bvalid_s),
    .m_axil_bready(u_xdma_0_top_m_axil_bready_s),
    .m_axil_bresp(u_xdma_0_top_m_axil_bresp_s),
    .m_axil_arvalid(u_xdma_0_top_m_axil_arvalid_s),
    .m_axil_arready(u_xdma_0_top_m_axil_arready_s),
    .m_axil_araddr(u_xdma_0_top_m_axil_araddr_s),
    .m_axil_arprot(u_xdma_0_top_m_axil_arprot_s),
    .m_axil_rvalid(u_xdma_0_top_m_axil_rvalid_s),
    .m_axil_rready(u_xdma_0_top_m_axil_rready_s),
    .m_axil_rdata(u_xdma_0_top_m_axil_rdata_s),
    .m_axil_rresp(u_xdma_0_top_m_axil_rresp_s),
    .msi_enable(msi_enable_o),
    .msix_enable(msix_enable_o),
    .msi_vector_width(msi_vector_width_o),
    .usr_irq_req(usr_irq_req_i),
    .usr_irq_ack(usr_irq_ack_o),
    .user_lnk_up(u_xdma_0_top_user_lnk_up_s),
    .pci_exp_txp(u_xdma_0_top_pci_exp_txp_s),
    .pci_exp_txn(u_xdma_0_top_pci_exp_txn_s),
    .pci_exp_rxp(u_soc_top_PCIE_EP_EXP_RX_p_s),
    .pci_exp_rxn(u_soc_top_PCIE_EP_EXP_RX_n_s),
    .c2h_sts_0(/*open*/),
    .h2c_sts_0(/*open*/),
    .c2h_sts_1(/*open*/),
    .h2c_sts_1(/*open*/)
    //input ports
    //output ports
    //inout ports
);


//u_ddr4_0_top instance
ddr4_0 u_ddr4_0_top(
    .c0_sys_clk_p(u_soc_top_DDR4_REF_CLK_p_s),
    .c0_sys_clk_n(u_soc_top_DDR4_REF_CLK_n_s),
    .sys_rst(u_uncore_top_ddr_rst_s),
    .c0_ddr4_ui_clk(u_ddr4_0_top_c0_ddr4_ui_clk_s),
    .c0_ddr4_aresetn(~u_ddr_rst_sync_dout_s),
    .c0_ddr4_reset_n(u_ddr4_0_top_c0_ddr4_reset_n_s),
    .c0_ddr4_ui_clk_sync_rst(u_ddr4_0_top_c0_ddr4_ui_clk_sync_rst_s),
    .dbg_clk(/*open*/),
    .dbg_bus(/*open*/),
    .c0_ddr4_s_axi_ctrl_awvalid(1'b0),
    .c0_ddr4_s_axi_ctrl_awready(/*open*/),
    .c0_ddr4_s_axi_ctrl_awaddr(32'b0),
    .c0_ddr4_s_axi_ctrl_wvalid(1'b0),
    .c0_ddr4_s_axi_ctrl_wready(/*open*/),
    .c0_ddr4_s_axi_ctrl_wdata(32'b0),
    .c0_ddr4_s_axi_ctrl_bvalid(/*open*/),
    .c0_ddr4_s_axi_ctrl_bready(1'b1),
    .c0_ddr4_s_axi_ctrl_bresp(/*open*/),
    .c0_ddr4_s_axi_ctrl_arvalid(1'b0),
    .c0_ddr4_s_axi_ctrl_arready(/*open*/),
    .c0_ddr4_s_axi_ctrl_araddr(32'b0),
    .c0_ddr4_s_axi_ctrl_rvalid(/*open*/),
    .c0_ddr4_s_axi_ctrl_rready(1'b1),
    .c0_ddr4_s_axi_ctrl_rdata(/*open*/),
    .c0_ddr4_s_axi_ctrl_rresp(/*open*/),
    .c0_ddr4_s_axi_awid(u_ddr4_0_top_c0_ddr4_s_axi_awid_s),
    .c0_ddr4_s_axi_awvalid(u_ddr4_0_top_c0_ddr4_s_axi_awvalid_s),
    .c0_ddr4_s_axi_awready(u_ddr4_0_top_c0_ddr4_s_axi_awready_s),
    .c0_ddr4_s_axi_awaddr(u_ddr4_0_top_c0_ddr4_s_axi_awaddr_s[32:0]),
    .c0_ddr4_s_axi_awlen(u_ddr4_0_top_c0_ddr4_s_axi_awlen_s),
    .c0_ddr4_s_axi_awsize(u_ddr4_0_top_c0_ddr4_s_axi_awsize_s),
    .c0_ddr4_s_axi_awburst(u_ddr4_0_top_c0_ddr4_s_axi_awburst_s),
    .c0_ddr4_s_axi_awlock(u_ddr4_0_top_c0_ddr4_s_axi_awlock_s),
    .c0_ddr4_s_axi_awcache(u_ddr4_0_top_c0_ddr4_s_axi_awcache_s),
    .c0_ddr4_s_axi_awprot(u_ddr4_0_top_c0_ddr4_s_axi_awprot_s),
    .c0_ddr4_s_axi_awqos(4'b0),
    .c0_ddr4_s_axi_wvalid(u_ddr4_0_top_c0_ddr4_s_axi_wvalid_s),
    .c0_ddr4_s_axi_wready(u_ddr4_0_top_c0_ddr4_s_axi_wready_s),
    .c0_ddr4_s_axi_wlast(u_ddr4_0_top_c0_ddr4_s_axi_wlast_s),
    .c0_ddr4_s_axi_wdata(u_ddr4_0_top_c0_ddr4_s_axi_wdata_s),
    .c0_ddr4_s_axi_wstrb(u_ddr4_0_top_c0_ddr4_s_axi_wstrb_s),
    .c0_ddr4_s_axi_bid(u_ddr4_0_top_c0_ddr4_s_axi_bid_s),
    .c0_ddr4_s_axi_bvalid(u_ddr4_0_top_c0_ddr4_s_axi_bvalid_s),
    .c0_ddr4_s_axi_bready(u_ddr4_0_top_c0_ddr4_s_axi_bready_s),
    .c0_ddr4_s_axi_bresp(u_ddr4_0_top_c0_ddr4_s_axi_bresp_s),
    .c0_ddr4_s_axi_arid(u_ddr4_0_top_c0_ddr4_s_axi_arid_s),
    .c0_ddr4_s_axi_arvalid(u_ddr4_0_top_c0_ddr4_s_axi_arvalid_s),
    .c0_ddr4_s_axi_arready(u_ddr4_0_top_c0_ddr4_s_axi_arready_s),
    .c0_ddr4_s_axi_araddr(u_ddr4_0_top_c0_ddr4_s_axi_araddr_s[32:0]),
    .c0_ddr4_s_axi_arlen(u_ddr4_0_top_c0_ddr4_s_axi_arlen_s),
    .c0_ddr4_s_axi_arsize(u_ddr4_0_top_c0_ddr4_s_axi_arsize_s),
    .c0_ddr4_s_axi_arburst(u_ddr4_0_top_c0_ddr4_s_axi_arburst_s),
    .c0_ddr4_s_axi_arlock(u_ddr4_0_top_c0_ddr4_s_axi_arlock_s),
    .c0_ddr4_s_axi_arcache(u_ddr4_0_top_c0_ddr4_s_axi_arcache_s),
    .c0_ddr4_s_axi_arprot(u_ddr4_0_top_c0_ddr4_s_axi_arprot_s),
    .c0_ddr4_s_axi_arqos(4'b0),
    .c0_ddr4_s_axi_rid(u_ddr4_0_top_c0_ddr4_s_axi_rid_s),
    .c0_ddr4_s_axi_rvalid(u_ddr4_0_top_c0_ddr4_s_axi_rvalid_s),
    .c0_ddr4_s_axi_rready(u_ddr4_0_top_c0_ddr4_s_axi_rready_s),
    .c0_ddr4_s_axi_rdata(u_ddr4_0_top_c0_ddr4_s_axi_rdata_s),
    .c0_ddr4_s_axi_rresp(u_ddr4_0_top_c0_ddr4_s_axi_rresp_s),
    .c0_ddr4_s_axi_rlast(u_ddr4_0_top_c0_ddr4_s_axi_rlast_s),
    .c0_ddr4_act_n(u_ddr4_0_top_c0_ddr4_act_n_s),
    .c0_ddr4_adr(u_ddr4_0_top_c0_ddr4_adr_s),
    .c0_ddr4_ba(u_ddr4_0_top_c0_ddr4_ba_s),
    .c0_ddr4_bg(u_ddr4_0_top_c0_ddr4_bg_s),
    .c0_ddr4_cke(u_ddr4_0_top_c0_ddr4_cke_s),
    .c0_ddr4_odt(u_ddr4_0_top_c0_ddr4_odt_s),
    .c0_ddr4_cs_n(u_ddr4_0_top_c0_ddr4_cs_n_s),
    .c0_ddr4_ck_t(u_ddr4_0_top_c0_ddr4_ck_t_s),
    .c0_ddr4_ck_c(u_ddr4_0_top_c0_ddr4_ck_c_s),
    .c0_ddr4_dm_dbi_n(u_ddr4_0_top_c0_ddr4_dm_dbi_n),
    .c0_ddr4_dq(u_ddr4_0_top_c0_ddr4_dq),
    .c0_ddr4_dqs_c(u_ddr4_0_top_c0_ddr4_dqs_c),
    .c0_ddr4_dqs_t(u_ddr4_0_top_c0_ddr4_dqs_t),
    .c0_init_calib_complete(u_ddr4_0_top_c0_init_calib_complete_s),
    .c0_ddr4_interrupt(/*open*/)
    //input ports
    //output ports
    //inout ports
);


//u_NV_nvdla_top instance
NV_nvdla_top u_NV_nvdla_top(
    .dla_csb_clk(u_uncore_top_dla_csb_clk_s),
    .dla_core_clk(u_uncore_top_dla_core_clk_s),
    .dla_reset_rstn(u_uncore_top_mac_rst_n_s),
    .psel(u_NV_nvdla_top_pselX_s),
    .penable(u_NV_nvdla_top_penable_s),
    .pwrite(u_NV_nvdla_top_pwrite_s),
    .paddr(u_NV_nvdla_top_paddr_s),
    .pwdata(u_NV_nvdla_top_pwdata_s),
    .pstrb(4'b0),
    .pprot(1'b0),
    .pready(u_NV_nvdla_top_pready_s),
    .prdata(u_NV_nvdla_top_prdata_s),
    .pslverr(u_NV_nvdla_top_pslverr_s),
    .nvdla_core2dbb_aw_awid(u_NV_nvdla_top_nvdla_core2dbb_aw_awid_s),
    .nvdla_core2dbb_aw_awvalid(u_NV_nvdla_top_nvdla_core2dbb_aw_awvalid_s),
    .nvdla_core2dbb_aw_awready(u_NV_nvdla_top_nvdla_core2dbb_aw_awready_s),
    .nvdla_core2dbb_aw_awaddr(u_NV_nvdla_top_nvdla_core2dbb_aw_awaddr_s),
    .nvdla_core2dbb_aw_awlen(u_NV_nvdla_top_nvdla_core2dbb_aw_awlen_s),
    .nvdla_core2dbb_aw_awsize(u_NV_nvdla_top_nvdla_core2dbb_aw_awsize_s),
    .nvdla_core2dbb_aw_awburst(u_NV_nvdla_top_nvdla_core2dbb_aw_awburst_s),
    .nvdla_core2dbb_aw_awlock(u_NV_nvdla_top_nvdla_core2dbb_aw_awlock_s),
    .nvdla_core2dbb_aw_awcache(u_NV_nvdla_top_nvdla_core2dbb_aw_awcache_s),
    .nvdla_core2dbb_aw_awprot(u_NV_nvdla_top_nvdla_core2dbb_aw_awprot_s),
    .nvdla_core2dbb_aw_awqos(/*open*/),
    .nvdla_core2dbb_aw_awregion(/*open*/),
    .nvdla_core2dbb_aw_awuser(/*open*/),
    .nvdla_core2dbb_w_wid(/*open*/),
    .nvdla_core2dbb_w_wvalid(u_NV_nvdla_top_nvdla_core2dbb_w_wvalid_s),
    .nvdla_core2dbb_w_wready(u_NV_nvdla_top_nvdla_core2dbb_w_wready_s),
    .nvdla_core2dbb_w_wlast(u_NV_nvdla_top_nvdla_core2dbb_w_wlast_s),
    .nvdla_core2dbb_w_wdata(u_NV_nvdla_top_nvdla_core2dbb_w_wdata_s),
    .nvdla_core2dbb_w_wstrb(u_NV_nvdla_top_nvdla_core2dbb_w_wstrb_s),
    .nvdla_core2dbb_w_wuser(/*open*/),
    .nvdla_core2dbb_b_bid({2'b0,u_NV_nvdla_top_nvdla_core2dbb_b_bid_s}),
    .nvdla_core2dbb_b_bvalid(u_NV_nvdla_top_nvdla_core2dbb_b_bvalid_s),
    .nvdla_core2dbb_b_bready(u_NV_nvdla_top_nvdla_core2dbb_b_bready_s),
    .nvdla_core2dbb_b_bresp(u_NV_nvdla_top_nvdla_core2dbb_b_bresp_s),
    .nvdla_core2dbb_b_buser(32'b0),
    .nvdla_core2dbb_ar_arid(u_NV_nvdla_top_nvdla_core2dbb_ar_arid_s),
    .nvdla_core2dbb_ar_arvalid(u_NV_nvdla_top_nvdla_core2dbb_ar_arvalid_s),
    .nvdla_core2dbb_ar_arready(u_NV_nvdla_top_nvdla_core2dbb_ar_arready_s),
    .nvdla_core2dbb_ar_araddr(u_NV_nvdla_top_nvdla_core2dbb_ar_araddr_s),
    .nvdla_core2dbb_ar_arlen(u_NV_nvdla_top_nvdla_core2dbb_ar_arlen_s),
    .nvdla_core2dbb_ar_arsize(u_NV_nvdla_top_nvdla_core2dbb_ar_arsize_s),
    .nvdla_core2dbb_ar_arburst(u_NV_nvdla_top_nvdla_core2dbb_ar_arburst_s),
    .nvdla_core2dbb_ar_arlock(u_NV_nvdla_top_nvdla_core2dbb_ar_arlock_s),
    .nvdla_core2dbb_ar_arcache(u_NV_nvdla_top_nvdla_core2dbb_ar_arcache_s),
    .nvdla_core2dbb_ar_arprot(u_NV_nvdla_top_nvdla_core2dbb_ar_arprot_s),
    .nvdla_core2dbb_ar_arqos(/*open*/),
    .nvdla_core2dbb_ar_arregion(/*open*/),
    .nvdla_core2dbb_ar_aruser(/*open*/),
    .nvdla_core2dbb_r_rid({2'b0,u_NV_nvdla_top_nvdla_core2dbb_r_rid_s}),
    .nvdla_core2dbb_r_rvalid(u_NV_nvdla_top_nvdla_core2dbb_r_rvalid_s),
    .nvdla_core2dbb_r_rready(u_NV_nvdla_top_nvdla_core2dbb_r_rready_s),
    .nvdla_core2dbb_r_rdata(u_NV_nvdla_top_nvdla_core2dbb_r_rdata_s),
    .nvdla_core2dbb_r_rresp(u_NV_nvdla_top_nvdla_core2dbb_r_rresp_s),
    .nvdla_core2dbb_r_rlast(u_NV_nvdla_top_nvdla_core2dbb_r_rlast_s),
    .nvdla_core2dbb_r_ruser(32'b0),
    .nvdla_core2cvsram_aw_awid(u_NV_nvdla_top_nvdla_core2cvsram_aw_awid_s),
    .nvdla_core2cvsram_aw_awvalid(u_NV_nvdla_top_nvdla_core2cvsram_aw_awvalid_s),
    .nvdla_core2cvsram_aw_awready(u_NV_nvdla_top_nvdla_core2cvsram_aw_awready_s),
    .nvdla_core2cvsram_aw_awaddr(u_NV_nvdla_top_nvdla_core2cvsram_aw_awaddr_s),
    .nvdla_core2cvsram_aw_awlen(u_NV_nvdla_top_nvdla_core2cvsram_aw_awlen_s),
    .nvdla_core2cvsram_aw_awsize(u_NV_nvdla_top_nvdla_core2cvsram_aw_awsize_s),
    .nvdla_core2cvsram_aw_awburst(u_NV_nvdla_top_nvdla_core2cvsram_aw_awburst_s),
    .nvdla_core2cvsram_aw_awlock(u_NV_nvdla_top_nvdla_core2cvsram_aw_awlock_s),
    .nvdla_core2cvsram_aw_awcache(u_NV_nvdla_top_nvdla_core2cvsram_aw_awcache_s),
    .nvdla_core2cvsram_aw_awprot(u_NV_nvdla_top_nvdla_core2cvsram_aw_awprot_s),
    .nvdla_core2cvsram_aw_awqos(/*open*/),
    .nvdla_core2cvsram_aw_awregion(/*open*/),
    .nvdla_core2cvsram_aw_awuser(/*open*/),
    .nvdla_core2cvsram_w_wid(/*open*/),
    .nvdla_core2cvsram_w_wvalid(u_NV_nvdla_top_nvdla_core2cvsram_w_wvalid_s),
    .nvdla_core2cvsram_w_wready(u_NV_nvdla_top_nvdla_core2cvsram_w_wready_s),
    .nvdla_core2cvsram_w_wlast(u_NV_nvdla_top_nvdla_core2cvsram_w_wlast_s),
    .nvdla_core2cvsram_w_wdata(u_NV_nvdla_top_nvdla_core2cvsram_w_wdata_s),
    .nvdla_core2cvsram_w_wstrb(u_NV_nvdla_top_nvdla_core2cvsram_w_wstrb_s),
    .nvdla_core2cvsram_w_wuser(/*open*/),
    .nvdla_core2cvsram_b_bid({2'b0,u_NV_nvdla_top_nvdla_core2cvsram_b_bid_s}),
    .nvdla_core2cvsram_b_bvalid(u_NV_nvdla_top_nvdla_core2cvsram_b_bvalid_s),
    .nvdla_core2cvsram_b_bready(u_NV_nvdla_top_nvdla_core2cvsram_b_bready_s),
    .nvdla_core2cvsram_b_bresp(u_NV_nvdla_top_nvdla_core2cvsram_b_bresp_s),
    .nvdla_core2cvsram_b_buser(32'b0),
    .nvdla_core2cvsram_ar_arid(u_NV_nvdla_top_nvdla_core2cvsram_ar_arid_s),
    .nvdla_core2cvsram_ar_arvalid(u_NV_nvdla_top_nvdla_core2cvsram_ar_arvalid_s),
    .nvdla_core2cvsram_ar_arready(u_NV_nvdla_top_nvdla_core2cvsram_ar_arready_s),
    .nvdla_core2cvsram_ar_araddr(u_NV_nvdla_top_nvdla_core2cvsram_ar_araddr_s),
    .nvdla_core2cvsram_ar_arlen(u_NV_nvdla_top_nvdla_core2cvsram_ar_arlen_s),
    .nvdla_core2cvsram_ar_arsize(u_NV_nvdla_top_nvdla_core2cvsram_ar_arsize_s),
    .nvdla_core2cvsram_ar_arburst(u_NV_nvdla_top_nvdla_core2cvsram_ar_arburst_s),
    .nvdla_core2cvsram_ar_arlock(u_NV_nvdla_top_nvdla_core2cvsram_ar_arlock_s),
    .nvdla_core2cvsram_ar_arcache(u_NV_nvdla_top_nvdla_core2cvsram_ar_arcache_s),
    .nvdla_core2cvsram_ar_arprot(u_NV_nvdla_top_nvdla_core2cvsram_ar_arprot_s),
    .nvdla_core2cvsram_ar_arqos(/*open*/),
    .nvdla_core2cvsram_ar_arregion(/*open*/),
    .nvdla_core2cvsram_ar_aruser(/*open*/),
    .nvdla_core2cvsram_r_rid({2'b0,u_NV_nvdla_top_nvdla_core2cvsram_r_rid_s}),
    .nvdla_core2cvsram_r_rvalid(u_NV_nvdla_top_nvdla_core2cvsram_r_rvalid_s),
    .nvdla_core2cvsram_r_rready(u_NV_nvdla_top_nvdla_core2cvsram_r_rready_s),
    .nvdla_core2cvsram_r_rdata(u_NV_nvdla_top_nvdla_core2cvsram_r_rdata_s),
    .nvdla_core2cvsram_r_rresp(u_NV_nvdla_top_nvdla_core2cvsram_r_rresp_s),
    .nvdla_core2cvsram_r_rlast(u_NV_nvdla_top_nvdla_core2cvsram_r_rlast_s),
    .nvdla_core2cvsram_r_ruser(32'b0),
    .nvdla_intr(u_NV_nvdla_top_nvdla_intr_s)
    //input ports
    //output ports
    //inout ports
);


//u_ddr_rst_sync instance
stdcc_rstn_sync2 u_ddr_rst_sync(
    //input ports
    .clk(u_ddr4_0_top_c0_ddr4_ui_clk_s),
    .rstn(u_uncore_top_ddr_rst_s),
    //output ports
    .dout(u_ddr_rst_sync_dout_s)
    //inout ports
);

//u_pcie_xclk_to_single instance
pcie_xclk_to_single u_pcie_xclk_to_single(
    //input ports
    .PCIE_REFCLK_p(u_soc_top_PCIE_EP_REFCLK_p_s),
    .PCIE_REFCLK_n(u_soc_top_PCIE_EP_REFCLK_n_s),
    //output ports
    .sys_clk_gt(u_pcie_xclk_to_single_sys_clk_gt_s),
    .sys_clk(u_pcie_xclk_to_single_sys_clk_s)
    //inout ports
);

endmodule
