// This system-verilog module was generated by Vega
//               Please do not edit!

//---------------------------------------------------------------------------
//                                                                           
//              Inspur Confidential                                          
// Copyright (c) 2021 Inspur. All rights reserved
//                                                                           
// File    : /nfs/work/shared/aipu.work/zhangqian06/workspace/zhangqian06.aipu.default/design_repo/rtl/soc_top/rtl/sv/uncore_top.sv
// Author  : Inspur Xi'an R&D                                                
// History : 2021-Nov-23 09:58:32 AM - Created    
//                                                                           
//---------------------------------------------------------------------------

module uncore_top(
    sys_clk_i,
    sys_rst_n_i,
    pcie_clk_i,
    pcie_hot_rstn_i,
    jtag_rst_sync_bypass_i,
    riscv_clk_o,
    riscv_core_clk_o,
    riscv_rst_o,
    riscv_debug_rst_o,
    riscv_debug_clk_o,
    riscv_rtc_toggle_o,
    per_clk_o,
    core_nic_rst_n_o,
    por_rstn_sync_o,
    dla_csb_clk_o,
    dla_core_clk_o,
    mac_rst_n_o,
    dma_clk_o,
    dma_rst_n_o,
    ddr_rst_o,
    boot_strap_i,
    pcie_msi_enable_i,
    pcie_msix_enable_i,
    ddr_initial_done_i,
    pcie_user_lnk_up_i,
    riscv_debug_dmactive_i,
    riscv_debug_dmactiveack_o,
    uart_rxd_i,
    uart_txd_o,
    u_core_top_AWID_AXI_UNCORE_SLV,
    u_core_top_AWVALID_AXI_UNCORE_SLV,
    u_core_top_AWREADY_AXI_UNCORE_SLV,
    u_core_top_AWADDR_AXI_UNCORE_SLV,
    u_core_top_AWLEN_AXI_UNCORE_SLV,
    u_core_top_AWSIZE_AXI_UNCORE_SLV,
    u_core_top_AWBURST_AXI_UNCORE_SLV,
    u_core_top_AWLOCK_AXI_UNCORE_SLV,
    u_core_top_AWCACHE_AXI_UNCORE_SLV,
    u_core_top_AWPROT_AXI_UNCORE_SLV,
    u_core_top_WVALID_AXI_UNCORE_SLV,
    u_core_top_WREADY_AXI_UNCORE_SLV,
    u_core_top_WLAST_AXI_UNCORE_SLV,
    u_core_top_WDATA_AXI_UNCORE_SLV,
    u_core_top_WSTRB_AXI_UNCORE_SLV,
    u_core_top_BID_AXI_UNCORE_SLV,
    u_core_top_BVALID_AXI_UNCORE_SLV,
    u_core_top_BREADY_AXI_UNCORE_SLV,
    u_core_top_BRESP_AXI_UNCORE_SLV,
    u_core_top_ARID_AXI_UNCORE_SLV,
    u_core_top_ARVALID_AXI_UNCORE_SLV,
    u_core_top_ARREADY_AXI_UNCORE_SLV,
    u_core_top_ARADDR_AXI_UNCORE_SLV,
    u_core_top_ARLEN_AXI_UNCORE_SLV,
    u_core_top_ARSIZE_AXI_UNCORE_SLV,
    u_core_top_ARBURST_AXI_UNCORE_SLV,
    u_core_top_ARLOCK_AXI_UNCORE_SLV,
    u_core_top_ARCACHE_AXI_UNCORE_SLV,
    u_core_top_ARPROT_AXI_UNCORE_SLV,
    u_core_top_RID_AXI_UNCORE_SLV,
    u_core_top_RVALID_AXI_UNCORE_SLV,
    u_core_top_RREADY_AXI_UNCORE_SLV,
    u_core_top_RLAST_AXI_UNCORE_SLV,
    u_core_top_RDATA_AXI_UNCORE_SLV,
    u_core_top_RRESP_AXI_UNCORE_SLV,
    timer0_int_ovf,
    timer0_int_cmp,
    timer1_int_ovf,
    timer1_int_cmp,
    sw_rst_req_prewarning_int,
    sw_int0,
    sw_int1,
    scu_int,
    pcie_int,
    uart_int,
    pcie_int_ack_i
);
input         sys_clk_i;
input         sys_rst_n_i;
input         pcie_clk_i;
input         pcie_hot_rstn_i;
input         jtag_rst_sync_bypass_i;

output        riscv_clk_o;
output        riscv_core_clk_o;
output        riscv_rst_o;
output        riscv_debug_rst_o;
output        riscv_debug_clk_o;
output        riscv_rtc_toggle_o;
output        per_clk_o;
output        core_nic_rst_n_o;
output        por_rstn_sync_o;
output        dla_csb_clk_o;
output        dla_core_clk_o;
output        mac_rst_n_o;
output        dma_clk_o;
output        dma_rst_n_o;
output        ddr_rst_o;

input         boot_strap_i;
input         pcie_msi_enable_i;
input         pcie_msix_enable_i;
input         pcie_user_lnk_up_i;
input         ddr_initial_done_i;
input         riscv_debug_dmactive_i;
output        riscv_debug_dmactiveack_o;

input         uart_rxd_i;
output        uart_txd_o;

input  [10:0] u_core_top_AWID_AXI_UNCORE_SLV;
input         u_core_top_AWVALID_AXI_UNCORE_SLV;
output        u_core_top_AWREADY_AXI_UNCORE_SLV;
input  [31:0] u_core_top_AWADDR_AXI_UNCORE_SLV;
input  [7:0]  u_core_top_AWLEN_AXI_UNCORE_SLV;
input  [2:0]  u_core_top_AWSIZE_AXI_UNCORE_SLV;
input  [1:0]  u_core_top_AWBURST_AXI_UNCORE_SLV;
input         u_core_top_AWLOCK_AXI_UNCORE_SLV;
input  [3:0]  u_core_top_AWCACHE_AXI_UNCORE_SLV;
input  [2:0]  u_core_top_AWPROT_AXI_UNCORE_SLV;
input         u_core_top_WVALID_AXI_UNCORE_SLV;
output        u_core_top_WREADY_AXI_UNCORE_SLV;
input         u_core_top_WLAST_AXI_UNCORE_SLV;
input  [31:0] u_core_top_WDATA_AXI_UNCORE_SLV;
input  [3:0]  u_core_top_WSTRB_AXI_UNCORE_SLV;
output [10:0] u_core_top_BID_AXI_UNCORE_SLV;
output        u_core_top_BVALID_AXI_UNCORE_SLV;
input         u_core_top_BREADY_AXI_UNCORE_SLV;
output [1:0]  u_core_top_BRESP_AXI_UNCORE_SLV;
input  [10:0] u_core_top_ARID_AXI_UNCORE_SLV;
input         u_core_top_ARVALID_AXI_UNCORE_SLV;
output        u_core_top_ARREADY_AXI_UNCORE_SLV;
input  [31:0] u_core_top_ARADDR_AXI_UNCORE_SLV;
input  [7:0]  u_core_top_ARLEN_AXI_UNCORE_SLV;
input  [2:0]  u_core_top_ARSIZE_AXI_UNCORE_SLV;
input  [1:0]  u_core_top_ARBURST_AXI_UNCORE_SLV;
input         u_core_top_ARLOCK_AXI_UNCORE_SLV;
input  [3:0]  u_core_top_ARCACHE_AXI_UNCORE_SLV;
input  [2:0]  u_core_top_ARPROT_AXI_UNCORE_SLV;
output [10:0] u_core_top_RID_AXI_UNCORE_SLV;
output        u_core_top_RVALID_AXI_UNCORE_SLV;
input         u_core_top_RREADY_AXI_UNCORE_SLV;
output        u_core_top_RLAST_AXI_UNCORE_SLV;
output [31:0] u_core_top_RDATA_AXI_UNCORE_SLV;
output [1:0]  u_core_top_RRESP_AXI_UNCORE_SLV;

output        timer0_int_ovf;
output        timer0_int_cmp;
output        timer1_int_ovf;
output        timer1_int_cmp;
output        sw_rst_req_prewarning_int;
output        sw_int0;
output        sw_int1;
output        scu_int;
output        pcie_int;
output        uart_int;
input  [2:0]  pcie_int_ack_i;

// input wires

// output wires

// internal wires
wire         per_apb_penable;
wire         per_apb_pselx;
wire         per_apb_pwrite;
wire [31:0]  per_apb_paddr;
wire [31:0]  per_apb_pwdata;
wire [31:0]  per_apb_prdata;
wire         per_apb_pready;
wire         per_apb_pslverr;

wire [31:0]  u_scu_top_ahb_haddr_s;
wire         u_scu_top_ahb_hready_s;
wire         u_scu_top_ahb_hselx_s;
wire [2:0]   u_scu_top_ahb_hsize_s;
wire [1:0]   u_scu_top_ahb_htrans_s;
wire [31:0]  u_scu_top_ahb_hwdata_s;
wire         u_scu_top_ahb_hwrite_s;
wire [31:0]  u_scu_top_ahb_rdata_s;
wire         u_scu_top_ahb_readyout_s;
wire [1:0]   u_scu_top_ahb_resp_s;

wire         u_scu_top_per_clk_s;
wire         u_scu_top_uncore_nic_rst_n_s;
wire         u_scu_top_uart_clk_s;
wire         u_scu_top_uart_kernel_clk_s;
wire         u_scu_top_uart_rst_n_s;
wire         u_scu_top_timer0_ahb_clk_s;
wire         u_scu_top_timer0_kernel_clk_s;
wire         u_scu_top_timer0_rst_n_s;
wire         u_scu_top_timer1_ahb_clk_s;
wire         u_scu_top_timer1_kernel_clk_s;
wire         u_scu_top_timer1_rst_n_s;


// input assign

// output assign
assign per_clk_o = u_scu_top_per_clk_s;


// internal assign

//u_cpu_subsys instance
cpu_subsys u_cpu_subsys(
    .u_scu_top_per_clk_i(u_scu_top_per_clk_s),
    .u_scu_top_uncore_nic_rst_n_i(u_scu_top_uncore_nic_rst_n_s),
    .u_uncore_top_jtag_rst_sync_bypass_i(jtag_rst_sync_bypass_i),
    .u_per_apb_penable_o (per_apb_penable),
    .u_per_apb_pselx_o   (per_apb_pselx  ),
    .u_per_apb_pwrite_o  (per_apb_pwrite ),
    .u_per_apb_paddr_o   (per_apb_paddr  ),
    .u_per_apb_hwdata_o  (per_apb_pwdata ),
    .u_per_apb_hrdata_i  (per_apb_prdata ),
    .u_per_apb_hready_i  (per_apb_pready ),
    .u_per_apb_slverr_i  (per_apb_pslverr),
    .u_scu_top_ahb_hselx_o(u_scu_top_ahb_hselx_s),
    .u_scu_top_ahb_hready_o(u_scu_top_ahb_hready_s),
    .u_scu_top_ahb_htrans_o(u_scu_top_ahb_htrans_s),
    .u_scu_top_ahb_hsize_o(u_scu_top_ahb_hsize_s),
    .u_scu_top_ahb_hwrite_o(u_scu_top_ahb_hwrite_s),
    .u_scu_top_ahb_haddr_o(u_scu_top_ahb_haddr_s),
    .u_scu_top_ahb_hwdata_o(u_scu_top_ahb_hwdata_s),
    .u_scu_top_ahb_rdata_i(u_scu_top_ahb_rdata_s),
    .u_scu_top_ahb_resp_i(u_scu_top_ahb_resp_s),
    .u_scu_top_ahb_readyout_i(u_scu_top_ahb_readyout_s),
    .u_uncore_top_AWID_AXI_UNCORE_SLV_i(u_core_top_AWID_AXI_UNCORE_SLV),
    .u_uncore_top_AWVALID_AXI_UNCORE_SLV_i(u_core_top_AWVALID_AXI_UNCORE_SLV),
    .u_uncore_top_AWREADY_AXI_UNCORE_SLV_o(u_core_top_AWREADY_AXI_UNCORE_SLV),
    .u_uncore_top_AWADDR_AXI_UNCORE_SLV_i(u_core_top_AWADDR_AXI_UNCORE_SLV),
    .u_uncore_top_AWLEN_AXI_UNCORE_SLV_i(u_core_top_AWLEN_AXI_UNCORE_SLV),
    .u_uncore_top_AWSIZE_AXI_UNCORE_SLV_i(u_core_top_AWSIZE_AXI_UNCORE_SLV),
    .u_uncore_top_AWBURST_AXI_UNCORE_SLV_i(u_core_top_AWBURST_AXI_UNCORE_SLV),
    .u_uncore_top_AWLOCK_AXI_UNCORE_SLV_i(u_core_top_AWLOCK_AXI_UNCORE_SLV),
    .u_uncore_top_AWCACHE_AXI_UNCORE_SLV_i(u_core_top_AWCACHE_AXI_UNCORE_SLV),
    .u_uncore_top_AWPROT_AXI_UNCORE_SLV_i(u_core_top_AWPROT_AXI_UNCORE_SLV),
    .u_uncore_top_WVALID_AXI_UNCORE_SLV_i(u_core_top_WVALID_AXI_UNCORE_SLV),
    .u_uncore_top_WREADY_AXI_UNCORE_SLV_o(u_core_top_WREADY_AXI_UNCORE_SLV),
    .u_uncore_top_WLAST_AXI_UNCORE_SLV_i(u_core_top_WLAST_AXI_UNCORE_SLV),
    .u_uncore_top_WDATA_AXI_UNCORE_SLV_i(u_core_top_WDATA_AXI_UNCORE_SLV),
    .u_uncore_top_WSTRB_AXI_UNCORE_SLV_i(u_core_top_WSTRB_AXI_UNCORE_SLV),
    .u_uncore_top_BID_AXI_UNCORE_SLV_o(u_core_top_BID_AXI_UNCORE_SLV),
    .u_uncore_top_BVALID_AXI_UNCORE_SLV_o(u_core_top_BVALID_AXI_UNCORE_SLV),
    .u_uncore_top_BREADY_AXI_UNCORE_SLV_i(u_core_top_BREADY_AXI_UNCORE_SLV),
    .u_uncore_top_BRESP_AXI_UNCORE_SLV_o(u_core_top_BRESP_AXI_UNCORE_SLV),
    .u_uncore_top_ARID_AXI_UNCORE_SLV_i(u_core_top_ARID_AXI_UNCORE_SLV),
    .u_uncore_top_ARVALID_AXI_UNCORE_SLV_i(u_core_top_ARVALID_AXI_UNCORE_SLV),
    .u_uncore_top_ARREADY_AXI_UNCORE_SLV_o(u_core_top_ARREADY_AXI_UNCORE_SLV),
    .u_uncore_top_ARADDR_AXI_UNCORE_SLV_i(u_core_top_ARADDR_AXI_UNCORE_SLV),
    .u_uncore_top_ARLEN_AXI_UNCORE_SLV_i(u_core_top_ARLEN_AXI_UNCORE_SLV),
    .u_uncore_top_ARSIZE_AXI_UNCORE_SLV_i(u_core_top_ARSIZE_AXI_UNCORE_SLV),
    .u_uncore_top_ARBURST_AXI_UNCORE_SLV_i(u_core_top_ARBURST_AXI_UNCORE_SLV),
    .u_uncore_top_ARLOCK_AXI_UNCORE_SLV_i(u_core_top_ARLOCK_AXI_UNCORE_SLV),
    .u_uncore_top_ARCACHE_AXI_UNCORE_SLV_i(u_core_top_ARCACHE_AXI_UNCORE_SLV),
    .u_uncore_top_ARPROT_AXI_UNCORE_SLV_i(u_core_top_ARPROT_AXI_UNCORE_SLV),
    .u_uncore_top_RID_AXI_UNCORE_SLV_o(u_core_top_RID_AXI_UNCORE_SLV),
    .u_uncore_top_RVALID_AXI_UNCORE_SLV_o(u_core_top_RVALID_AXI_UNCORE_SLV),
    .u_uncore_top_RREADY_AXI_UNCORE_SLV_i(u_core_top_RREADY_AXI_UNCORE_SLV),
    .u_uncore_top_RLAST_AXI_UNCORE_SLV_o(u_core_top_RLAST_AXI_UNCORE_SLV),
    .u_uncore_top_RDATA_AXI_UNCORE_SLV_o(u_core_top_RDATA_AXI_UNCORE_SLV),
    .u_uncore_top_RRESP_AXI_UNCORE_SLV_o(u_core_top_RRESP_AXI_UNCORE_SLV)
    //input ports
    //output ports
    //inout ports
);

//u_per_subsys instance
per_subsys u_per_subsys(
    .u_per_clk_i                 (u_scu_top_per_clk_s          ),
    .u_per_rst_n_i               (u_scu_top_uncore_nic_rst_n_s ),
    .u_uart_clk_i                (u_scu_top_uart_clk_s         ),
    .u_uart_kernel_clk_i         (u_scu_top_uart_kernel_clk_s  ),
    .u_uart_rst_n_i              (u_scu_top_uart_rst_n_s       ),
    .u_timer0_apb_clk_i          (u_scu_top_timer0_ahb_clk_s   ),
    .u_timer0_kernel_clk_i       (u_scu_top_timer0_kernel_clk_s),
    .u_timer0_rst_n_i            (u_scu_top_timer0_rst_n_s     ),
    .u_timer1_apb_clk_i          (u_scu_top_timer1_ahb_clk_s   ),
    .u_timer1_kernel_clk_i       (u_scu_top_timer1_kernel_clk_s),
    .u_timer1_rst_n_i            (u_scu_top_timer1_rst_n_s     ),
    .u_per_apb_penable_i         (per_apb_penable              ),
    .u_per_apb_pselx_i           (per_apb_pselx                ),
    .u_per_apb_paddr_i           (per_apb_paddr                ),
    .u_per_apb_pwrite_i          (per_apb_pwrite               ),
    .u_per_apb_pwdata_i          (per_apb_pwdata               ),
    .u_per_apb_prdata_o          (per_apb_prdata               ),
    .u_per_apb_pready_o          (per_apb_pready               ),
    .u_per_apb_pslverr_o         (per_apb_pslverr              ),
    .u_apb_uart_txd_o            (uart_txd_o                   ),
    .u_apb_uart_rxd_i            (uart_rxd_i                   ),
    .u_apb_uart_int_o            (uart_int                     ),
    .u_apb_timer_timer0_int_ovf_o(timer0_int_ovf               ),
    .u_apb_timer_timer0_int_cmp_o(timer0_int_cmp               ),
    .u_apb_timer_timer1_int_ovf_o(timer1_int_ovf               ),
    .u_apb_timer_timer1_int_cmp_o(timer1_int_cmp               )
);


//u_scu_top instance
scu_top u_scu_top(
    //input ports
    .sys_clk_i(sys_clk_i),
    .por_rstn_i(sys_rst_n_i),
    .jtag_trstn_i(1'b0),
    .jtag_rst_sync_bypass_i(jtag_rst_sync_bypass_i),
    .pcie_clk_i(pcie_clk_i),
    .pcie_hot_rstn_i(pcie_hot_rstn_i),
    .pcie_int_ack_i(pcie_int_ack_i),
    .pcie_msi_enable_i(pcie_msi_enable_i),
    .pcie_msix_enable_i(pcie_msix_enable_i),
    .ahb_sel_i(u_scu_top_ahb_hselx_s),
    .ahb_ready_i(u_scu_top_ahb_hready_s),
    .ahb_trans_i(u_scu_top_ahb_htrans_s),
    .ahb_size_i(u_scu_top_ahb_hsize_s),
    .ahb_write_i(u_scu_top_ahb_hwrite_s),
    .ahb_addr_i({8'b0,u_scu_top_ahb_haddr_s[15:0]}),
    .ahb_wdata_i(u_scu_top_ahb_hwdata_s),
    .riscv_debug_dmactive_i(riscv_debug_dmactive_i),
    .boot_strap_i(boot_strap_i),
    .ddr_initial_done_i(ddr_initial_done_i),
    .pcie_user_lnk_up_i(pcie_user_lnk_up_i),
    //output ports
    .ahb_readyout_o(u_scu_top_ahb_readyout_s),
    .ahb_resp_o(u_scu_top_ahb_resp_s),
    .ahb_rdata_o(u_scu_top_ahb_rdata_s),
    .riscv_debug_dmactiveack_o(riscv_debug_dmactiveack_o),
    .scu_int_o(scu_int),
    .sw_int0_o(sw_int0),
    .sw_int1_o(sw_int1),
    .wdt_prewarning_int_o(),
    .sw_rst_req_prewarning_int_o(sw_rst_req_prewarning_int),
    .pcie_int_o(pcie_int),
    .riscv_clk_o(riscv_clk_o),
    .riscv_core_clk_o(riscv_core_clk_o),
    .riscv_rtc_toggle_o(riscv_rtc_toggle_o),
    .riscv_debug_clk_o(riscv_debug_clk_o),
    .dma_clk_o(dma_clk_o),
    .per_clk_o(u_scu_top_per_clk_s),
    .uart_clk_o(u_scu_top_uart_clk_s),
    .uart_kernel_clk_o(u_scu_top_uart_kernel_clk_s),
    .timer0_ahb_clk_o(u_scu_top_timer0_ahb_clk_s),
    .timer0_kernel_clk_o(u_scu_top_timer0_kernel_clk_s),
    .timer1_ahb_clk_o(u_scu_top_timer1_ahb_clk_s),
    .timer1_kernel_clk_o(u_scu_top_timer1_kernel_clk_s),
    .dla_core_clk_o(dla_core_clk_o),
    .dla_csb_clk_o(dla_csb_clk_o),
    .por_rstn_sync_o(por_rstn_sync_o),
    .riscv_debug_rst_o(riscv_debug_rst_o),
    .riscv_rst_o(riscv_rst_o),
    .core_nic_rst_n_o(core_nic_rst_n_o),
    .uncore_nic_rst_n_o(u_scu_top_uncore_nic_rst_n_s),
    .uart_rst_n_o(u_scu_top_uart_rst_n_s),
    .timer0_rst_n_o(u_scu_top_timer0_rst_n_s),
    .timer1_rst_n_o(u_scu_top_timer1_rst_n_s),
    .jtag2ahb_rst_n_o( ),
    .dma_rst_n_o(dma_rst_n_o),
    .mac_rst_n_o(mac_rst_n_o),
    .ddr_rst_o(ddr_rst_o)
    //inout ports
);

endmodule
